Minishell: builtins_exit_pwd.c File Reference
builtins_exit_pwd.c File Reference
#include "minishell.h"
Functions
static int pre_check_long_overflow (const char *nptr)
Get the number of digits in a string.
static int check_long_overflow (const char *nptr, long temp, int digit_cmd, int digit_temp)
Check if a long overflowed.
static int exit_arg (char **cmd, t_token *token, long temp, int i)
Evaluates the arguments of the exit command.
int builtins_exit (char **cmd, t_token *token)
Builtin "exit" command.
int builtins_pwd (char **cmd)
Builtin "pwd" command.
Function Documentation
builtins_exit()
int builtins_exit (char ** cmd, t_token * token)
Builtin "exit" command.
Handles the bahaviour of the builtin exit command. Quits minishell, taking one optional argument for the exit code.
Author
kfan
Parameters
cmd command arguments
token command token
Returns
int
Return values
success Returns 0 on success, 1 on error.
Definition at line 152 of file builtins_exit_pwd.c.
References t_token::error, exit_arg(), t_token::exit_code, ft_isdigit(), t_token::nmb_of_cmd, and str_equals().
Referenced by check_builtins().
builtins_pwd()
int builtins_pwd (char ** cmd)
Builtin "pwd" command.
Handles the behaviour of the pwd command, printing the current working directory to stdout. New: If getcwd fails, it will return 0. We have no idea why, but bash does it so we do it too Note: error return 2 if it has a flag
Author
kfan
Parameters
cmd command arguments
Returns
int
Return values
success Always returns 0.
Definition at line 205 of file builtins_exit_pwd.c.
References ft_printf(), and str_equals().
Referenced by check_builtins().
check_long_overflow()
static int check_long_overflow (const char * nptr, long temp, int digit_cmd, int digit_temp) static
Check if a long overflowed.
Checks if a long overflowed by comparing its digits to a string representation of the wanted number.
Author
kfan
Parameters
nptr string to compare the number to
temp number to check for overflows
digit_cmd number of digits in the string
digit_temp number of digits in the number
Returns
int
Return values
success Returns 0 if it did not overflow, 1 if it did.
Definition at line 68 of file builtins_exit_pwd.c.
References pre_check_long_overflow().
Referenced by exit_arg().
exit_arg()
static int exit_arg (char ** cmd, t_token * token, long temp, int i) static
Evaluates the arguments of the exit command.
Checks for errors in the arguments of exit. If more than one argument is given it throws an error. If a non-numeric argument is given it throws an error. If the number is too large (over LONG_MAX) it throws an error.
Author
kfan
Parameters
cmd command arguments
token token to change the exit code in
temp converted number (ignored)
i character index. Always set to 0!
Returns
int
Return values
success Always returns 0.
Definition at line 108 of file builtins_exit_pwd.c.
References check_long_overflow(), t_token::exit_code, ft_atoi(), ft_atol(), ft_isdigit(), is_space(), and str_equals().
Referenced by builtins_exit().
pre_check_long_overflow()
static int pre_check_long_overflow (const char * nptr) static
Get the number of digits in a string.
Count the number of digits in the string representation of a number. The string may begin with an arbitrarry amount of whitespace, followed by a single '+' or '-' symbol, follwoed by digits. The number may be prepended by any amount of zeroes and they will not be counted towards the length of the number.
Author
kfan
Parameters
nptr string to check
Returns
int
Return values
digit_cmd Number of digits in the string
Definition at line 32 of file builtins_exit_pwd.c.
References ft_isdigit().
Referenced by check_long_overflow().