Minishell: builtins_pipes.c File Reference
builtins_pipes.c File Reference
#include "minishell.h"
Functions
int builtins_pipe_fd_out (t_cmds *cmds, int *fd)
Lorem Ipsum.
int builtins_pipe_fd_in (t_cmds *cmds, int *fd)
Lorem Ipsum.
Function Documentation
builtins_pipe_fd_in()
int builtins_pipe_fd_in (t_cmds * cmds, int * fd)
Lorem Ipsum.
Lorem Ipsum Dolor Si Amet
Author
kfan
Parameters
cmds foo
fd foo
Returns
int
Return values
foo bar
Definition at line 61 of file builtins_pipes.c.
References t_cmds::cmd, and str_equals().
Referenced by check_builtins().
builtins_pipe_fd_out()
int builtins_pipe_fd_out (t_cmds * cmds, int * fd)
Lorem Ipsum.
Lorem Ipsum Dolor Si Amet
Author
kfan
Parameters
cmds foo
fd foo
Returns
int
Return values
foo bar
Definition at line 28 of file builtins_pipes.c.
References t_cmds::cmd, t_cmds::outfile, and str_equals().
Referenced by check_builtins().