Minishell: builtins_export_unset.c File Reference
builtins_export_unset.c File Reference
#include "minishell.h"
Functions
static int unset_export (t_token *token, char *temp)
Unsets an environment variable.
static int add_envp_export (char *cmd, t_token *token)
Add a variable to envp.
int add_envp (char *cmd, t_token *token, int i, int j)
Add entry to envp.
int builtins_export (char **cmd, t_token *token, int k, int i)
Builtin "export" command.
int builtins_unset (char **cmd, char **envp, t_token *token, int k)
Builtin "unset" command.
Function Documentation
add_envp()
int add_envp (char * cmd, t_token * token, int i, int j)
Add entry to envp.
Adds an environment variable to envp.
Author
kfan
Parameters
cmd value to add
token Token to set environment variables
i index 1 (Always set to 0!)
j index 2 (Always set to 0!)
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 108 of file builtins_export_unset.c.
References add_array(), add_envp_export(), t_token::data, t_data::envp, t_token::envp, ft_free_split(), ft_strncmp(), and remove_array().
Referenced by builtins_export(), and replace_pwd().
add_envp_export()
static int add_envp_export (char * cmd, t_token * token) static
Add a variable to envp.
Adds a variable to envp for the export command. If the valie is already present it should be overwritten.
Author
kfan
Parameters
cmd name of the variable to export
token token to set environment variables with
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 70 of file builtins_export_unset.c.
References add_array(), attach_quote(), t_token::data, t_data::envp_export, t_token::envp_export, ft_free_split(), ft_strjoin(), sort_array(), and unset_export().
Referenced by add_envp(), and builtins_export().
builtins_export()
int builtins_export (char ** cmd, t_token * token, int k, int i)
Builtin "export" command.
Handles the behaviour of the export command. Sets or changes an environment variable to a given value.
Author
kfan
Parameters
cmd command arguments
token command token
k mystery integer
i mystery integer 2 - electric boogaloo
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 153 of file builtins_export_unset.c.
References add_envp(), add_envp_export(), t_token::envp_export, ft_isalnum(), ft_isalpha(), t_token::nmb_of_cmd, print_array(), and str_equals().
Referenced by check_builtins().
builtins_unset()
int builtins_unset (char ** cmd, char ** envp, t_token * token, int k)
Builtin "unset" command.
Handles the behaviour of the builtin unset command. Deletes an environment variable from envp.
Author
kfan
Parameters
cmd command arguments
envp environment variables
token command token
k mystery integer, very spooky
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 197 of file builtins_export_unset.c.
References t_token::data, t_data::envp, ft_free_split(), ft_strlen(), ft_strncmp(), t_token::nmb_of_cmd, remove_array(), str_equals(), and unset_export().
Referenced by check_builtins().
unset_export()
static int unset_export (t_token * token, char * temp) static
Unsets an environment variable.
Unsets (deletes) an environment variable from the given token's environment variable list.
Author
kfan
Parameters
token token to unset the variable in
temp variable to unset
Returns
int
Return values
succes Returns 0 on success, 1 otherwise.
Definition at line 29 of file builtins_export_unset.c.
References t_token::data, t_data::envp_export, t_token::envp_export, ft_free_split(), ft_strncmp(), and remove_array().
Referenced by add_envp_export(), and builtins_unset().