Minishell: builtins_cd.c File Reference
builtins_cd.c File Reference
#include "minishell.h"
Functions
static int make_path (char *path, char *prefix, char **temp)
Joins two strings to a path.
static int replace_pwd (char *oldpath, t_token *token)
Replace PWD with a new path.
static int check_and_change_path (char **envp, char *path, t_token *token)
Changes the current working directory.
static int change_dir (char *path, char **envp, t_token *token)
Changes the current working directory.
int builtins_cd (char **cmd, char **envp, t_token *token)
Builtin "cd" command.
Function Documentation
builtins_cd()
int builtins_cd (char ** cmd, char ** envp, t_token * token)
Builtin "cd" command.
Handles the behaviour of the builtin cd command. Changes the current working directory to a given relative or absolute path. If getcwd fails, it wil lreturn with 0. We don't know why, but bash does it so we do it too. :P
Author
kfan
Parameters
cmd command arguments
envp environment variables
token command token
Returns
int
Return values
success Returns 0 on success, 1 otherwise
Definition at line 178 of file builtins_cd.c.
References change_dir(), t_token::nmb_of_cmd, and str_equals().
Referenced by check_builtins().
change_dir()
static int change_dir (char * path, char ** envp, t_token * token) static
Changes the current working directory.
Checks if path is empty. If so, changes the current working directory to the home directory. Otherwise it changes the directory to path using check_and_change_path().
Author
kfan
Parameters
path path to new working directory
envp environment variables
token token to change the variables with
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 139 of file builtins_cd.c.
References check_and_change_path(), and ft_strncmp().
Referenced by builtins_cd().
check_and_change_path()
static int check_and_change_path (char ** envp, char * path, t_token * token) static
Changes the current working directory.
Changes the path of the current working directory, as long as the path is a valid directory. If the path is "-" it changes the current working directory to OLDPWD. Caches the current working directory before changing it and calling replace_pwd() to update the environment variables.
Author
kfan
Parameters
envp environment variables
path path to the new working directory
token Token to change the variables with
Returns
int
Return values
succes Returns 0 on success, 1 otherwise.
Definition at line 99 of file builtins_cd.c.
References check_and_change_path(), ft_printf(), ft_strncmp(), replace_pwd(), and str_equals().
Referenced by change_dir(), and check_and_change_path().
make_path()
static int make_path (char * path, char * prefix, char ** temp) static
Joins two strings to a path.
Joins two paths using strjoin and updates the string inside of temp accordingly (*temp == result).
Author
kfan
Parameters
path path to contatenate with
prefix Prefix to concatenate the path on
temp Adress to write the result to
Returns
int
Return values
succes Returns 0 on success, 1 otherwise.
Definition at line 30 of file builtins_cd.c.
References ft_calloc(), ft_strlcpy(), and ft_strlen().
Referenced by replace_pwd().
replace_pwd()
static int replace_pwd (char * oldpath, t_token * token) static
Replace PWD with a new path.
Updates the PWD environmental variable with the current working directory. Fetches the cwd using getcwd() and copies the old working directory to the OLDPWD envronment variable.
The internal variable path is limited to 4096 characters since that is the maximum length of a path in linux.
Author
kfan
Parameters
oldpath old working directory
token Token to export the variables with
Returns
int
Return values
success Returns 0 on success, 1 otherwise
Definition at line 61 of file builtins_cd.c.
References add_envp(), and make_path().
Referenced by check_and_change_path().