Minishell: builtins_echo_env.c File Reference
builtins_echo_env.c File Reference
#include "minishell.h"
Functions
static int echo_flag (char **cmd)
echo command flag check
int builtins_echo (char **cmd)
Builtin "echo" command.
int builtins_env (char **envp, char **cmd)
Builtin env command.
Function Documentation
builtins_echo()
int builtins_echo (char ** cmd)
Builtin "echo" command.
This function handles the behaviour of the echo command. Writes a string to stdout that can be piped to other commands.
Author
kfan
Parameters
cmd command arguments and flags of echo
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 69 of file builtins_echo_env.c.
References echo_flag(), and ft_strlen().
Referenced by check_builtins().
builtins_env()
int builtins_env (char ** envp, char ** cmd)
Builtin env command.
Prints out the list of environment variables. error and exit code 125 if arg exists just like env fails
Author
kfan
Parameters
envp environment variables
cmd args
Returns
int
Return values
return Always returns 0.
Definition at line 104 of file builtins_echo_env.c.
References print_array(), and str_equals().
Referenced by check_builtins().
echo_flag()
static int echo_flag (char ** cmd) static
echo command flag check
Checks if the echo command was called with a flag.
Author
kfan
Parameters
cmd command arguments
Returns
int
Return values
i Position of the first non-flag argument?
Definition at line 30 of file builtins_echo_env.c.
References ft_strlen().
Referenced by builtins_echo().