Minishell: error.c File Reference
error.c File Reference
#include "minishell.h"
Functions
void syntax_error (char *str, t_token *token)
Indicates a syntax error.
int error (char *msg)
Prints an error to stderr and returns 1.
void warn (char *msg)
Prints a warning to stdout.
void debug (char *msg)
Prints a debug message to stdout.
Function Documentation
debug()
void debug (char * msg)
Prints a debug message to stdout.
This function prints a debug message to the standard output (fd = 1). All messages are prepended with "\033[1;44m DEBUG \033[22;0m -> " and terminated with a newline. DEBUG must be defined as 1 for this function to execute, otherwise it will not do anything!
Author
kmautner
Parameters
msg message to print
Definition at line 113 of file error.c.
References DEBUG, and ft_strlen().
Referenced by destroy_history(), history_add(), history_write(), init_history(), read_history_file(), and read_input().
error()
int error (char * msg)
Prints an error to stderr and returns 1.
This function prints an error message to the standard error and returns 1. All messages are prepended with "\033[1;41m ERROR \033[22;0m -> ". Uses perror to print the message.
Author
kmautner
Parameters
msg message to print, may be NULL
Returns
int
Return values
return Always returns 1.
Definition at line 58 of file error.c.
References ft_strjoin().
Referenced by destroy_history(), history_write(), signal_init(), signal_init1(), signal_init_execve(), signal_init_here_doc(), and signal_init_post_execve().
syntax_error()
void syntax_error (char * str, t_token * token)
Indicates a syntax error.
This function indicates a syntax error in the token that is currently being processed and stops the processing of this token.
Author
kfan
Parameters
str message printed
token token in which the error occurred
Definition at line 32 of file error.c.
References t_token::error, t_token::exit_code, and ft_strlen().
Referenced by check_cmd(), check_temp(), clean_infile(), clean_name(), clean_name_no_expand(), clean_outfile(), and redir().
warn()
void warn (char * msg)
Prints a warning to stdout.
This function prints a warning message to the standard output (fd = 1). All messages are prepended with "\033[1;43m WARNING \033[22;0m -> " and terminated with a newline.
Author
kmautner
Parameters
msg message to print, may be NULL
Definition at line 90 of file error.c.
References ft_strlen().
Referenced by init_history(), and read_history_file().