Minishell: error_mini.c File Reference
error_mini.c File Reference
#include "minishell.h"
Functions
<<<<<<< HEAD=======> > > > > > void mini_error (char *str, char *arg, t_token *token, int *fd)
Indicates a mini error.
static void command_not_found (char *cmd)
Raises a command not found error.
void execve_error (char *cmd, char *path, t_token *token, DIR *dir)
Raises an execve error.
void open_error (char *str, t_token *token, int *fd, int k)
Indicates an open error.
Function Documentation
command_not_found()
static void command_not_found (char * cmd) static
Raises a command not found error.
Raises a command not found error, writing an error message to stdout (fd = 2). The message is formatted as follows "<cmd>: command not found".
Author
kfan
Parameters
cmd command that caused the error (may be NULL)
Definition at line 64 of file error_mini.c.
References ft_strlen().
Referenced by execve_error().
execve_error()
void execve_error (char * cmd, char * path, t_token * token, DIR * dir)
Raises an execve error.
Raises an execve error and prints an error message to stdout (fd = 2). Depending on the type of execve error (permission denied or command not found) the printing is handled by mini_error() or command_not_found().
Author
kfan
Parameters
cmd command that caused the error
path path to the faulty executable
token token in which the error occurred
dir directory in which the error occurred
Definition at line 87 of file error_mini.c.
References command_not_found(), t_token::error, t_token::exit_code, ft_strlen(), ft_strncmp(), and mini_error().
Referenced by child().
mini_error()
<<<<<<< HEAD======= > > > > > > void mini_error (char * str, char * arg, t_token * token, int * fd)
Indicates a mini error.
This function indicates a mini error in the token that is currently being processed and will not stop the processing of this token.
Author
kfan
Parameters
str message printed
token token in which the error occurred
Definition at line 33 of file error_mini.c.
References t_token::exit_code, and ft_strlen().
Referenced by clean_infile(), clean_outfile(), and execve_error().
open_error()
void open_error (char * str, t_token * token, int * fd, int k)
Indicates an open error.
This function indicates an open error in the token that is currently being processed and stops the processing of this token.
Author
kfan
Parameters
str debug feature, unused
token token in which the error occurred.
Definition at line 128 of file error_mini.c.
References t_token::cmds, t_cmds::exit_code, and ft_strlen().
Referenced by ft_heredoc(), ft_redir_in1(), infile(), and outfile().