Minishell: ft_put.c File Reference
ft_put.c File Reference
#include "libft.h"
Functions
int ft_putchar (const char arg)
int ft_putstr (const char *arg)
int ft_putnbr (int n)
int ft_putnbruns (unsigned int n)
Function Documentation
ft_putchar()
int ft_putchar (const char arg)
Definition at line 15 of file ft_put.c.
Referenced by ft_flags(), ft_hex(), ft_hexaddress(), ft_ispercent(), ft_putnbr(), and ft_putnbruns().
ft_putnbr()
int ft_putnbr (int n)
Definition at line 39 of file ft_put.c.
References ft_putchar(), and ft_putnbr().
Referenced by ft_flags(), and ft_putnbr().
ft_putnbruns()
int ft_putnbruns (unsigned int n)
Definition at line 64 of file ft_put.c.
References ft_putchar(), and ft_putnbruns().
Referenced by ft_flags(), and ft_putnbruns().
ft_putstr()
int ft_putstr (const char * arg)
Definition at line 21 of file ft_put.c.
Referenced by ft_address(), and ft_flags().