Minishell: ft_split.c File Reference
ft_split.c File Reference
#include "libft.h"
Functions
static size_t ft_count (char const *s, char c)
static char * ft_newstring (char const *s, char c)
static void ft_free (char **array, int i)
static char ** ft_array (char const *s, char c, char **array)
char ** ft_split (char const *s, char c)
Function Documentation
ft_array()
static char ** ft_array (char const * s, char c, char ** array) static
Definition at line 73 of file ft_split.c.
References ft_count(), ft_free(), ft_newstring(), and ft_strlen().
Referenced by ft_split().
ft_count()
static size_t ft_count (char const * s, char c) static
Definition at line 17 of file ft_split.c.
Referenced by ft_array(), and ft_split().
ft_free()
static void ft_free (char ** array, int i) static
Definition at line 61 of file ft_split.c.
Referenced by ft_array(), ft_array(), ft_array(), and ft_array().
ft_newstring()
static char * ft_newstring (char const * s, char c) static
Definition at line 41 of file ft_split.c.
Referenced by ft_array().
ft_split()
char ** ft_split (char const * s, char c)
Definition at line 96 of file ft_split.c.
References ft_array(), and ft_count().
Referenced by get_path().