Minishell: ft_printf.c File Reference
ft_printf.c File Reference
#include "libft.h"
Functions
static int ft_iscon (char c)
static int ft_flags (const char *input, long arg)
static int ft_ispercent (const char *input)
static int ft_loop (const char *input, va_list args)
int ft_printf (const char *input,...)
Function Documentation
ft_flags()
static int ft_flags (const char * input, long arg) static
Definition at line 26 of file ft_printf.c.
References ft_address(), ft_hex(), ft_iscon(), ft_putchar(), ft_putnbr(), ft_putnbruns(), ft_putstr(), and input().
Referenced by ft_loop().
ft_iscon()
static int ft_iscon (char c) static
Definition at line 15 of file ft_printf.c.
Referenced by ft_flags(), and ft_ispercent().
ft_ispercent()
static int ft_ispercent (const char * input) static
Definition at line 50 of file ft_printf.c.
References ft_iscon(), ft_putchar(), and input().
Referenced by ft_loop().
ft_loop()
static int ft_loop (const char * input, va_list args) static
Definition at line 64 of file ft_printf.c.
References ft_flags(), ft_ispercent(), and input().
Referenced by ft_printf().
ft_printf()
int ft_printf (const char * input, ...)
Definition at line 91 of file ft_printf.c.
References ft_loop(), and input().
Referenced by builtins_pwd(), check_and_change_path(), clean_infile(), clean_outfile(), expand_exit_code(), print_array(), print_token(), and restore_fd().