Minishell: ft_hex.c File Reference
ft_hex.c File Reference
#include "libft.h"
Functions
int ft_hex (unsigned int n, int x)
static int ft_hexaddress (unsigned long n)
int ft_address (unsigned long n)
Function Documentation
ft_address()
int ft_address (unsigned long n)
Definition at line 65 of file ft_hex.c.
References ft_hexaddress(), and ft_putstr().
Referenced by ft_flags().
ft_hex()
int ft_hex (unsigned int n, int x)
Definition at line 15 of file ft_hex.c.
References ft_hex(), and ft_putchar().
Referenced by ft_flags(), and ft_hex().
ft_hexaddress()
static int ft_hexaddress (unsigned long n) static
Definition at line 40 of file ft_hex.c.
References ft_hexaddress(), and ft_putchar().
Referenced by ft_address(), and ft_hexaddress().