Minishell: get_next_line.c File Reference
get_next_line.c File Reference
#include "libft.h"
Functions
static char * ft_memdup (char *s, size_t size)
static char * ft_free (char **buffer)
static char * ft_alloc (char *buffer, char **ptr)
static char * ft_return (char **buffer, int i)
char * get_next_line (int fd)
Function Documentation
ft_alloc()
static char * ft_alloc (char * buffer, char ** ptr) static
Definition at line 34 of file get_next_line.c.
References BUFFER_SIZE, ft_calloc(), ft_free(), and ft_memcpy().
Referenced by get_next_line().
ft_free()
static char * ft_free (char ** buffer) static
Definition at line 26 of file get_next_line.c.
Referenced by ft_alloc(), ft_return(), and get_next_line().
ft_memdup()
static char * ft_memdup (char * s, size_t size) static
Definition at line 15 of file get_next_line.c.
References ft_calloc(), and ft_memcpy().
Referenced by ft_return().
ft_return()
static char * ft_return (char ** buffer, int i) static
Definition at line 61 of file get_next_line.c.
References ft_free(), and ft_memdup().
Referenced by get_next_line().
get_next_line()
char * get_next_line (int fd)
Definition at line 86 of file get_next_line.c.
References BUFFER_SIZE, ft_alloc(), ft_free(), ft_return(), and get_next_line().
Referenced by get_next_line(), and read_history_file().