Minishell: history.c File Reference
history.c File Reference
#include "minishell.h"
Functions
int history_add (t_history *history, char *command)
Add an entry to the history.
int read_history_file (t_history *history, int fd)
Reads history file into history.
int init_history (t_history *history)
Initialise the history of the minishell.
int history_write (t_history history)
Writes the current history to the history file.
void destroy_history (t_history *history)
Destroys the history of the minishell.
Function Documentation
destroy_history()
void destroy_history (t_history * history)
Destroys the history of the minishell.
This function destroys the current history. All entries are written to the history file using history_write() before the history is destroyed.
Author
kmautner
Parameters
history history struct
Definition at line 167 of file history.c.
References debug(), error(), history_write(), and t_history::list.
Referenced by free_all().
history_add()
int history_add (t_history * history, char * command)
Add an entry to the history.
This function adds a malloc'd string to the history. If an equal string is already the latest entry in history, it will get free'd and ignored.
Author
kmautner
Parameters
history history struct
command entry to add to history
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 29 of file history.c.
References debug(), HISTORY_MAX_SIZE, t_history::length, t_history::list, shift_array(), and str_equals().
Referenced by main(), and read_history_file().
history_write()
int history_write (t_history history)
Writes the current history to the history file.
This function opens the history file, truncates it and writes the current history to the file. Should the file not exist it will be created. If the file cannot be opened execution will stop and the current history will get lost. Write fails are ignored and may lead to a corrupted file.
Author
kmautner
Parameters
history history struct
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 136 of file history.c.
References debug(), error(), ft_strlen(), HISTORY_FILE, t_history::length, and t_history::list.
Referenced by destroy_history().
init_history()
int init_history (t_history * history)
Initialise the history of the minishell.
Function used to initialise the static data of the history. If the history file is present, its contents get read into the history using read_history_file().
Author
kmautner
Parameters
history history struct pointer
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 105 of file history.c.
References debug(), ft_bzero(), HISTORY_FILE, read_history_file(), and warn().
Referenced by init_main().
read_history_file()
int read_history_file (t_history * history, int fd)
Reads history file into history.
This funciton is used to open the history file and add its contents to the current history. Should the file not exist or be unopenable this function is skipped. Should the reading of the file fail it will stop execution at that point. Any entries after the fail will not get loaded into memory.
Author
kmautner
Parameters
history history struct
fd file descriptor of the opened history file
Returns
int
Return values
success Returns 0 on success, 1 on error.
Definition at line 66 of file history.c.
References debug(), ft_strlen(), get_next_line(), history_add(), and warn().
Referenced by init_history().