Minishell: minishell.h File Reference
minishell.h File Reference
#include "libft/libft.h"
#include <dirent.h>
#include <fcntl.h>
#include <readline/history.h>
#include <readline/readline.h>
#include <signal.h>
#include <stdio.h>
#include <sys/wait.h>
Data Structures
struct t_cmds
struct t_clean
struct t_data
Input data struct.
struct t_token
Struct containing a token.
struct t_history
Struct to save history data.
Macros
#define DEBUG 0
Debug status.
#define HISTORY_MAX_SIZE 100
Max size for history.
#define HISTORY_FILE ".minishell_history"
Location and name of the history file.
Functions
void print_token (t_token **token)
void make_tree (t_data *data)
Creates the tree of tokens to be processed.
int init_token (char **temp, t_token **token, t_data *data, int i)
Initialises a token array.
int make_cmd_list (char **temp, t_token *token)
Makes a command list of all split pipes.
char ** ft_cmd (char *temp, t_token *token, char **old)
Splits the command and separates them with spaces.
int redir (char *temp, t_token *token, int k)
Check token syntax for redirections.
int ft_heredoc (t_token *token, char *eof, char *file, int k)
Handles the functionality of a heredoc.
int clean_and_expand (t_token *token)
Clean and expand all tokens.
char * clean_name (char *temp, t_token *token, int count, char *file)
Expand input.
int get_rid_of_extra_space (char *temp)
void init_clean (t_clean *clean, int count, char *file)
char * clean_name_no_expand (char *temp, t_token *token, int count, char *file)
int join_envp_char (t_token *token, t_clean *clean, char *str)
int join_envp_str (t_token *token, t_clean *clean, char *str)
int join_envp (t_token *token, t_clean *clean, char **temp, int i)
void check_new_array (t_clean *clean)
char * expand_envp (char *temp, t_token *token, char *new, int quote)
int check_envp_count (char *temp)
char * wildcards (char *temp, t_token *token, t_clean *clean)
void syntax_error (char *str, t_token *token)
Indicates a syntax error.
void open_error (char *str, t_token *token, int *fd, int k)
Indicates an open error.
void mini_error (char *str, char *arg, t_token *token, int *fd)
Indicates a mini error.
void execve_error (char *cmd, char *path, t_token *token, DIR *dir)
Raises an execve error.
int pipex (t_token *token)
int outfile (t_token *token, int k)
char * get_path (char **cmd, char **envp)
int input (t_cmds *cmds, t_token *token)
int last_input (t_cmds *cmds, t_token *token)
int empty_pipe (int *fd)
void wait_pipes (t_token *token, int i, int status)
char * ft_charjoin (char *s1, char *s2)
Append a character to a string.
int inside_quote (char c, int quote)
Get the current quote state.
void close_unused_fd (t_token **token, int i)
void restore_fd (t_data *data, int *fd)
char * join_cmd (char *src, char *new)
int join_cmd_1 (t_token *token, int i, int j, char *file)
int join_cmd_2 (t_token *token, int i, int j, char *file)
void sort_array (char **input)
Sorts an array of strings.
void sort_array_wildcards (char **input)
char * attach_quote (char *temp)
Add quotation marks around a substring.
char ** copy_array_prefix (char **input, int y, int i, int j)
Copies an array of strings, adding a prefix to each string.
char ** copy_array (char **input)
Copies an array of strings.
char ** remove_array (char **input, int index, int y, int j)
Duplicate an array without the value at a given index.
char ** add_array (char **input, char *entry, int y)
Adds a string to an array of strings.
void print_array (char **temp)
Debug function to print an array of strings.
char ** ft_split_space (char *s)
char ** ft_split_cmd (char *s)
char ** ft_split_delimiter (char const *s)
char ** ft_split_pipe (char *s)
void ft_free (char **array, int i)
void ft_free_split (char **array)
Frees the result of an ft_split() call.
void ft_free_token (t_token **token)
Frees a token.
void free_heredoc (char *suffix, char *prefix, char *temp)
void small_free (t_token **token, int i)
Small version of ft_free_token()
int is_delimiter (char c1, char c2)
Checks if a given character is a delimiter.
int is_sym (char c1, char c2)
Checks which type a symbol is.
int is_quote (char c)
Checks if a character is a quote.
int is_space (char c)
Checks if a given character is a space.
int is_pipe (char c)
Checks if a given character is a pipe.
int sym_count (char c1, char c2, char *pin)
int delimiter_count (char c1, char c2)
Count the length of a delimiter.
char ** join_split (char ***old, char ***cmd, int i, int j)
Joins to arrays of strings together.
int builtins_echo (char **cmd)
Builtin "echo" command.
int builtins_cd (char **cmd, char **envp, t_token *token)
Builtin "cd" command.
int builtins_pwd (char **cmd)
Builtin "pwd" command.
int builtins_export (char **cmd, t_token *token, int k, int i)
Builtin "export" command.
int builtins_unset (char **cmd, char **envp, t_token *token, int k)
Builtin "unset" command.
int builtins_env (char **envp, char **cmd)
Builtin env command.
int builtins_exit (char **cmd, t_token *token)
Builtin "exit" command.
int add_envp (char *cmd, t_token *token, int i, int j)
Add entry to envp.
int builtins_pipe_fd_out (t_cmds *cmds, int *fd)
Lorem Ipsum.
int builtins_pipe_fd_in (t_cmds *cmds, int *fd)
Lorem Ipsum.
int error (char *msg)
Prints an error to stderr and returns 1.
void warn (char *msg)
Prints a warning to stdout.
void debug (char *msg)
Prints a debug message to stdout.
int signal_init (void)
Initlialisation function for the signal handling.
int signal_init1 (void)
Initialiser for the modified signal handlers.
int signal_init_here_doc (void)
Initialiser for the modified signal handlers.
int signal_init_execve (void)
Initialises the execve signal handler.
int signal_init_post_execve (void)
Initialiser for the modified signal handlers.
int history_add (t_history *history, char *command)
Add an entry to the history.
int init_history (t_history *history)
Initialise the history of the minishell.
void destroy_history (t_history *history)
Destroys the history of the minishell.
int str_equals (char *str1, char *str2)
Checks if two strings are equal.
void shift_array (char **array, int length)
Shifts an array of strings to the left by one position.
Variables
int g_sigrecv
Macro Definition Documentation
DEBUG
#define DEBUG 0
Debug status.
Author
kmautner
Indicates if minishell is in debug mode. By default (if not defined) this will be set to 0. Use the debug rule in the make file to compile minishell with debug mode enabled.
Definition at line 35 of file minishell.h.
Referenced by debug().
HISTORY_FILE
#define HISTORY_FILE ".minishell_history"
Location and name of the history file.
Author
kmautner
This macro defines the location and name of the file where the history is saved inbetween sessions. Default is ".minishell_history"
Definition at line 66 of file minishell.h.
Referenced by history_write(), and init_history().
HISTORY_MAX_SIZE
#define HISTORY_MAX_SIZE 100
Max size for history.
Author
kmautner
This macro defines the max size of the history. Default is 100 commands.
Definition at line 55 of file minishell.h.
Referenced by history_add().
Function Documentation
add_array()
char ** add_array (char ** input, char * entry, int y)
Adds a string to an array of strings.
Copies an array of strings and appends the given string entry to the array.
Parameters
input Array to append to
entry Entry to append
y Counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Appended array
Author
kfan
Definition at line 170 of file utils_array2.c.
References free_if_failed(), ft_strdup(), and input().
Referenced by add_envp(), add_envp_export(), get_files(), join_envp(), join_envp_char(), and join_envp_str().
add_envp()
int add_envp (char * cmd, t_token * token, int i, int j)
Add entry to envp.
Adds an environment variable to envp.
Author
kfan
Parameters
cmd value to add
token Token to set environment variables
i index 1 (Always set to 0!)
j index 2 (Always set to 0!)
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 112 of file builtins_export_unset.c.
References add_array(), add_envp_export(), t_token::data, t_data::envp, t_token::envp, ft_free_split(), ft_strncmp(), and remove_array().
Referenced by builtins_export(), and replace_pwd().
attach_quote()
char * attach_quote (char * temp)
Add quotation marks around a substring.
Adds quotation marks around a literal value inside a string. The literal value is detected by the presence of an '=' sign in front of it. If no '=' is found it returns a duplicate of the original string.
Parameters
temp String to add quotes to
Returns
char*
Return values
new Modified string
Author
kfan
Definition at line 135 of file utils_array1.c.
References ft_calloc(), ft_strdup(), ft_strlcpy(), and ft_strlen().
Referenced by add_envp_export(), and copy_array_prefix().
builtins_cd()
int builtins_cd (char ** cmd, char ** envp, t_token * token)
Builtin "cd" command.
Handles the behaviour of the builtin cd command. Changes the current working directory to a given relative or absolute path. If getcwd fails, it wil lreturn with 0. We don't know why, but bash does it so we do it too. :P
Author
kfan
Parameters
cmd command arguments
envp environment variables
token command token
Returns
int
Return values
success Returns 0 on success, 1 otherwise
Definition at line 177 of file builtins_cd.c.
References change_dir(), t_token::nmb_of_cmd, and str_equals().
Referenced by check_builtins().
builtins_echo()
int builtins_echo (char ** cmd)
Builtin "echo" command.
This function handles the behaviour of the echo command. Writes a string to stdout that can be piped to other commands.
Author
kfan
Parameters
cmd command arguments and flags of echo
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 69 of file builtins_echo_env.c.
References echo_flag(), and ft_strlen().
Referenced by check_builtins().
builtins_env()
int builtins_env (char ** envp, char ** cmd)
Builtin env command.
Prints out the list of environment variables. error and exit code 125 if arg exists just like env fails
Author
kfan
Parameters
envp environment variables
cmd args
Returns
int
Return values
return Always returns 0.
Definition at line 104 of file builtins_echo_env.c.
References print_array(), and str_equals().
Referenced by check_builtins().
builtins_exit()
int builtins_exit (char ** cmd, t_token * token)
Builtin "exit" command.
Handles the bahaviour of the builtin exit command. Quits minishell, taking one optional argument for the exit code.
Author
kfan
Parameters
cmd command arguments
token command token
Returns
int
Return values
success Returns 0 on success, 1 on error.
Definition at line 158 of file builtins_exit_pwd.c.
References t_token::error, exit_arg(), t_token::exit_code, ft_isdigit(), t_token::nmb_of_cmd, and str_equals().
Referenced by check_builtins().
builtins_export()
int builtins_export (char ** cmd, t_token * token, int k, int i)
Builtin "export" command.
Handles the behaviour of the export command. Sets or changes an environment variable to a given value.
Author
kfan
Parameters
cmd command arguments
token command token
k mystery integer
i mystery integer 2 - electric boogaloo
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 157 of file builtins_export_unset.c.
References add_envp(), add_envp_export(), t_token::envp_export, ft_isalnum(), ft_isalpha(), t_token::nmb_of_cmd, print_array(), and str_equals().
Referenced by check_builtins().
builtins_pipe_fd_in()
int builtins_pipe_fd_in (t_cmds * cmds, int * fd)
Lorem Ipsum.
Lorem Ipsum Dolor Si Amet
Author
kfan
Parameters
cmds foo
fd foo
Returns
int
Return values
foo bar
Definition at line 61 of file builtins_pipes.c.
References t_cmds::cmd, and str_equals().
Referenced by check_builtins().
builtins_pipe_fd_out()
int builtins_pipe_fd_out (t_cmds * cmds, int * fd)
Lorem Ipsum.
Lorem Ipsum Dolor Si Amet
Author
kfan
Parameters
cmds foo
fd foo
Returns
int
Return values
foo bar
Definition at line 28 of file builtins_pipes.c.
References t_cmds::cmd, t_cmds::outfile, and str_equals().
Referenced by check_builtins().
builtins_pwd()
int builtins_pwd (char ** cmd)
Builtin "pwd" command.
Handles the behaviour of the pwd command, printing the current working directory to stdout. New: If getcwd fails, it will return 0. We have no idea why, but bash does it so we do it too Note: error return 2 if it has a flag
Author
kfan
Parameters
cmd command arguments
Returns
int
Return values
success Always returns 0.
Definition at line 211 of file builtins_exit_pwd.c.
References ft_printf(), and str_equals().
Referenced by check_builtins().
builtins_unset()
int builtins_unset (char ** cmd, char ** envp, t_token * token, int k)
Builtin "unset" command.
Handles the behaviour of the builtin unset command. Deletes an environment variable from envp.
Author
kfan
Parameters
cmd command arguments
envp environment variables
token command token
k mystery integer, very spooky
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 201 of file builtins_export_unset.c.
References t_token::data, t_data::envp, ft_free_split(), ft_strlen(), ft_strncmp(), t_token::nmb_of_cmd, remove_array(), str_equals(), and unset_export().
Referenced by check_builtins().
check_envp_count()
int check_envp_count (char * temp)
Definition at line 16 of file parse7_expand_envp.c.
References ft_isalnum().
Referenced by clean_name_envp(), expand_envp(), and expand_heredoc().
check_new_array()
void check_new_array (t_clean * clean)
Definition at line 16 of file parse6b_clean_name_join_envp.c.
References t_clean::envp_temp, is_space(), and t_clean::new_array.
Referenced by check_split_envp().
clean_and_expand()
int clean_and_expand (t_token * token)
Clean and expand all tokens.
Clean and expand all commands, infiles and outfiles inside of all pipes in the list of tokens.
Author
kfan
Parameters
token List of tokens
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 178 of file parse5_clean_and_expand.c.
References clean_cmd_list(), clean_infile(), and clean_outfile().
Referenced by execute().
clean_name()
char * clean_name (char * temp, t_token * token, int count, char * file)
Expand input.
Expand environment variables in temp. Environment variables inside '' (single quotes) should not be expanded, otherwise they should always expand. Any extra space outside of quotes should be removed. count == 0 for cmd, otherwise for redir. Only create new cmd array if token->pipe == 0 ???
Author
kfan
Parameters
temp string to expand
token command token
count start index
file foo
Returns
char*
Return values
new clean.new on success, NULL otherwise.
Definition at line 229 of file parse6_clean_name.c.
References t_data::cmd_temp, t_token::data, ft_strdup(), init_clean(), is_space(), loop_str(), t_clean::new, t_clean::quote, syntax_error(), t_clean::temp, and t_token::wildcards.
Referenced by clean_cmd(), clean_infile(), clean_outfile(), ft_redir_in1(), ft_redir_out(), and wildcards().
clean_name_no_expand()
char * clean_name_no_expand (char * temp, t_token * token, int count, char * file)
Definition at line 66 of file parse6a_clean_name_no_expand.c.
References clean_name_char(), t_clean::count, t_clean::file, init_clean(), inside_quote(), is_space(), t_clean::new, t_clean::quote, and syntax_error().
Referenced by ft_redir_in1().
close_unused_fd()
void close_unused_fd (t_token ** token, int i)
Definition at line 95 of file utils.c.
References t_token::cmds, and t_cmds::fd.
Referenced by make_tree().
copy_array()
char ** copy_array (char ** input)
Copies an array of strings.
Copies an array of strings and returns the malloc'd copy. Currently only used to copy envp.
Parameters
input
Returns
char**
Return values
temp Malloc'd copy of the array.
Author
kfan
Definition at line 92 of file utils_array2.c.
References free_if_failed(), ft_strdup(), and input().
Referenced by init_main(), join_cmd_1(), join_cmd_2(), and join_envp_1().
copy_array_prefix()
char ** copy_array_prefix (char ** input, int y, int i, int j)
Copies an array of strings, adding a prefix to each string.
Copies an array of strings and adds the prefix "declare -x " to each string. Also uses attatch_quote() on each string before adding the prefix.
Parameters
input Array to copy
y Counter variable, ALWAYS SET TO 0!
i Counter variable, ALWAYS SET TO 0!
j Counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Malloc'd modified copy of the string array.
Author
kfan
Definition at line 50 of file utils_array2.c.
References attach_quote(), free_if_failed(), ft_strjoin(), and input().
Referenced by init_main().
debug()
void debug (char * msg)
Prints a debug message to stdout.
This function prints a debug message to the standard output (fd = 1). All messages are prepended with "\033[1;44m DEBUG \033[22;0m -> " and terminated with a newline. DEBUG must be defined as 1 for this function to execute, otherwise it will not do anything!
Author
kmautner
Parameters
msg message to print
Definition at line 113 of file error.c.
References DEBUG, and ft_strlen().
Referenced by destroy_history(), history_add(), history_write(), init_history(), read_history_file(), and read_input().
delimiter_count()
int delimiter_count (char c1, char c2)
Count the length of a delimiter.
Returns how long a delimiter is. Delimiters are:
;
&&
||
Parameters
c1 First character of the delimiter
c2 Second character of the delimiter
Returns
int
Return values
len Length of the delimiter
Author
kfan
Definition at line 80 of file utils_count.c.
Referenced by ft_count(), and ft_newstring().
destroy_history()
void destroy_history (t_history * history)
Destroys the history of the minishell.
This function destroys the current history. All entries are written to the history file using history_write() before the history is destroyed.
Author
kmautner
Parameters
history history struct
Definition at line 167 of file history.c.
References debug(), error(), history_write(), and t_history::list.
Referenced by free_all().
empty_pipe()
int empty_pipe (int * fd)
Definition at line 83 of file pipex_utils.c.
Referenced by input().
error()
int error (char * msg)
Prints an error to stderr and returns 1.
This function prints an error message to the standard error and returns 1. All messages are prepended with "\033[1;41m ERROR \033[22;0m -> ". Uses perror to print the message.
Author
kmautner
Parameters
msg message to print, may be NULL
Returns
int
Return values
return Always returns 1.
Definition at line 58 of file error.c.
References ft_strjoin().
Referenced by destroy_history(), history_write(), signal_init(), signal_init1(), signal_init_execve(), signal_init_here_doc(), and signal_init_post_execve().
execve_error()
void execve_error (char * cmd, char * path, t_token * token, DIR * dir)
Raises an execve error.
Raises an execve error and prints an error message to stdout (fd = 2). Depending on the type of execve error (permission denied or command not found) the printing is handled by mini_error() or command_not_found().
Author
kfan
Parameters
cmd command that caused the error
path path to the faulty executable
token token in which the error occurred
dir directory in which the error occurred
Definition at line 87 of file error_mini.c.
References command_not_found(), t_token::error, t_token::exit_code, ft_strlen(), ft_strncmp(), and mini_error().
Referenced by child().
expand_envp()
char * expand_envp (char * temp, t_token * token, char * new, int quote)
Definition at line 52 of file parse7_expand_envp.c.
References check_envp_count(), check_sys_envp_count(), t_token::envp, expand_exit_code(), ft_calloc(), ft_isalpha(), ft_strdup(), ft_strncmp(), and is_quote().
Referenced by clean_name_envp(), and expand_heredoc().
free_heredoc()
void free_heredoc (char * suffix, char * prefix, char * temp)
Definition at line 146 of file utils_free.c.
Referenced by expand_heredoc().
ft_charjoin()
char * ft_charjoin (char * s1, char * s2)
Append a character to a string.
This function joins a character to the end of a string. The result is stored as a new malloc'd string and returned.
Parameters
s1 String to join to
s2 Character to join
Returns
char *
Return values
ptr Malloc'd result string
Author
kfan
Definition at line 28 of file utils.c.
References ft_strlcpy(), and ft_strlen().
Referenced by clean_name_char(), clean_name_char(), and join_envp_char().
ft_cmd()
char ** ft_cmd (char * temp, t_token * token, char ** old)
Splits the command and separates them with spaces.
Split the temp cmd with a modified split to seperate the cmd and arg with space. Space inside a quote will not be skipped! Quotes and $ are still inside yet and will be cleaned and expanded later. Join the new split with previous split.
Example: "<infile echo >out 'hel lo' world$USER" will become:
echo
'hel lo'
world$USER
Author
kfan
Parameters
temp command to split
token token
old old split
Returns
char**
Return values
cmd Returns old, or NULL on error.
Definition at line 38 of file parse3_make_cmd_list.c.
References t_token::error, ft_split_space(), and join_split().
Referenced by join_envp(), and scan_pipe().
ft_free()
void ft_free (char ** array, int i)
Definition at line 43 of file utils_ft_split_delimiter.c.
Referenced by ft_array().
ft_free_split()
void ft_free_split (char ** array)
Frees the result of an ft_split() call.
Frees a 2-dimensional array like one returned by ft_split(). The array has to be NULL-terminated!
Parameters
array array to free
Author
kfan
Definition at line 25 of file utils_free.c.
Referenced by add_envp(), add_envp_export(), builtins_unset(), check_split_envp(), clean_cmd(), free_all(), ft_free_struct(), get_files(), init_main(), join_cmd_2(), join_envp_char(), join_envp_str(), make_tree(), scan_pipe(), split_pipe(), and unset_export().
ft_free_token()
void ft_free_token (t_token ** token)
Frees a token.
Frees a t_token struct.
Parameters
token t_token struct to free
t_token
Author
kfan
Definition at line 91 of file utils_free.c.
References ft_free_struct().
Referenced by make_tree().
ft_heredoc()
int ft_heredoc (t_token * token, char * eof, char * file, int k)
Handles the functionality of a heredoc.
Creates a temporary file for the user to write to when using a heredoc and deletes it afterwards.
Author
kfan
Parameters
token Command token
eof End of file indicator
Returns
int
Return values
fd File descriptor of the heredoc.
Definition at line 176 of file parse4a_redir_heredoc.c.
References is_quote(), open_error(), signal_init_here_doc(), and write_heredoc().
Referenced by ft_redir_in1().
ft_split_cmd()
char ** ft_split_cmd (char * s)
Definition at line 94 of file utils_ft_split_cmd.c.
References ft_array(), and ft_count().
Referenced by split_cmd().
ft_split_delimiter()
char ** ft_split_delimiter (char const * s)
Definition at line 106 of file utils_ft_split_delimiter.c.
References ft_array(), and ft_count().
Referenced by make_tree().
ft_split_pipe()
char ** ft_split_pipe (char * s)
Definition at line 94 of file utils_ft_split_pipe.c.
References ft_array(), and ft_count().
Referenced by split_pipe().
ft_split_space()
char ** ft_split_space (char * s)
Definition at line 94 of file utils_ft_split_space.c.
References ft_array(), and ft_count().
Referenced by check_split_envp(), and ft_cmd().
get_path()
char * get_path (char ** cmd, char ** envp)
Definition at line 56 of file pipex_utils.c.
References find_bin(), ft_free_pipex(), ft_split(), ft_strdup(), and ft_strncmp().
Referenced by input(), and last_input().
get_rid_of_extra_space()
int get_rid_of_extra_space (char * temp)
Definition at line 18 of file parse6a_clean_name_no_expand.c.
References is_space().
Referenced by clean_name_char(), and clean_name_char().
history_add()
int history_add (t_history * history, char * command)
Add an entry to the history.
This function adds a malloc'd string to the history. If an equal string is already the latest entry in history, it will get free'd and ignored.
Author
kmautner
Parameters
history history struct
command entry to add to history
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 29 of file history.c.
References debug(), HISTORY_MAX_SIZE, t_history::length, t_history::list, shift_array(), and str_equals().
Referenced by main(), and read_history_file().
init_clean()
void init_clean (t_clean * clean, int count, char * file)
Definition at line 52 of file parse6a_clean_name_no_expand.c.
References t_clean::count, t_clean::envp_temp, t_clean::file, t_clean::new, t_clean::new_array, t_clean::quote, t_clean::space, and t_clean::temp.
Referenced by clean_name(), and clean_name_no_expand().
init_history()
int init_history (t_history * history)
Initialise the history of the minishell.
Function used to initialise the static data of the history. If the history file is present, its contents get read into the history using read_history_file().
Author
kmautner
Parameters
history history struct pointer
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 105 of file history.c.
References debug(), ft_bzero(), HISTORY_FILE, read_history_file(), and warn().
Referenced by init_main().
init_token()
int init_token (char ** temp, t_token ** token, t_data * data, int i)
Initialises a token array.
Sets the parameters taken from data in every token of a token array.
Author
kfan
Parameters
temp command list
token array of t_token structs
data t_data struct
i length of the token array
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 195 of file parse2_init.c.
References t_token::cmds, t_token::data, t_token::delimiter, t_data::envp, t_token::envp, t_data::envp_export, t_token::envp_export, t_data::error, t_token::error, t_data::exit_code, t_token::exit_code, t_data::fd_in, t_token::fd_in, t_data::fd_out, t_token::fd_out, init_token1(), t_token::nmb_of_cmd, small_free(), and t_token::wildcards.
Referenced by make_token().
input()
int input (t_cmds * cmds, t_token * token)
Definition at line 78 of file pipex_input.c.
References check_builtins(), child(), t_cmds::cmd, empty_pipe(), t_token::envp, t_cmds::fd, get_path(), parent(), and t_cmds::pid.
Referenced by add_array(), copy_array(), copy_array_prefix(), filter(), filter_prefix(), ft_flags(), ft_ispercent(), ft_loop(), ft_printf(), pipex(), remove_array(), sort_array(), and sort_array_wildcards().
inside_quote()
int inside_quote (char c, int quote)
Get the current quote state.
Gets the current quote state. List of quote states and their values:
' = 1
" = 2 - ' " = 3
" ' = 4
Returns 0 if the current position is not inside a quotation marked block.
Parameters
c quote character
quote current quote state
Returns
int
Return values
state New quote state
Author
kfan
Definition at line 69 of file utils.c.
References is_quote().
Referenced by clean_name_no_expand(), find_star(), ft_count(), ft_count(), ft_count(), ft_count(), ft_newstring(), ft_newstring(), ft_newstring(), ft_newstring(), loop_str(), and name_count().
is_delimiter()
int is_delimiter (char c1, char c2)
Checks if a given character is a delimiter.
Checks if a character is the delimiter of a command. Some delimiters are made up of two characters and therefore require both values to be set so to be recognised properly!
Parameters
c1 first character of the delimiter
c2 second character of the delimiter (may be NULL)
Returns
int
Return values
delim Integer describing the delimiter.
; = 1
&& = 2
|| = 3 if none of these are detected, 0 is returned.
Author
kfan
Definition at line 88 of file utils_is.c.
Referenced by check_temp(), ft_count(), ft_newstring(), and init_token1().
is_pipe()
int is_pipe (char c)
Checks if a given character is a pipe.
Checks if a given character is a '|' pipe character.
Parameters
c character to check
Returns
int
Return values
success 1 if the character is a pipe, 0 otherwise.
Author
kfan
Definition at line 152 of file utils_is.c.
Referenced by check_cmd(), ft_count(), ft_newstring(), and split_cmd().
is_quote()
int is_quote (char c)
Checks if a character is a quote.
Checks if the character is a quotation mark and, if it is, what kind of quotation mark it is (single or double).
Parameters
c character to check
Returns
int
Return values
success 1 for single quotes, 2 for double quotes, 0 otherwise.
Author
kfan
Definition at line 112 of file utils_is.c.
Referenced by clean_name_char(), clean_name_char(), expand_envp(), ft_heredoc(), and inside_quote().
is_space()
int is_space (char c)
Checks if a given character is a space.
Checks if a given character is a space character. This includes ASCII indexes 9 - 13 alongside the ' ' space character.
Parameters
c character to check
Returns
int
Return values
success 1 if the character is a space, 0 otherwise.
Author
kfan
Definition at line 134 of file utils_is.c.
Referenced by check_cmd(), check_new_array(), check_temp(), clean_name(), clean_name_char(), clean_name_char(), clean_name_no_expand(), exit_arg(), ft_array(), ft_count(), ft_newstring(), get_rid_of_extra_space(), init_token1(), join_envp(), redir(), and scan_pipe().
is_sym()
int is_sym (char c1, char c2)
Checks which type a symbol is.
Checks for which type the given symbol is. The list of symbols and their return values are:
$ = 1
| = 2
<< = 3
< = 4
> = 5
>> = 6
; = 7
|| = 8
&& = 9
|| and && are only needed for the bonus. If no symbol is recognised, the function will return 0.
Parameters
c1 First character of the symbol
c2 Second character of the symbol
Returns
int
Return values
type Type of the symbol
Author
kfan
Definition at line 50 of file utils_is.c.
Referenced by ft_count(), ft_newstring(), name_count(), redir(), and scan_pipe().
join_cmd()
char * join_cmd (char * src, char * new)
Definition at line 132 of file utils.c.
References ft_strjoin().
join_cmd_1()
int join_cmd_1 (t_token * token, int i, int j, char * file)
Definition at line 96 of file utils_join.c.
References t_cmds::cmd, t_data::cmd_temp, t_token::cmds, copy_array(), t_token::data, t_token::error, and join_split().
Referenced by clean_cmd().
join_cmd_2()
int join_cmd_2 (t_token * token, int i, int j, char * file)
Definition at line 123 of file utils_join.c.
References t_cmds::cmd, t_data::cmd_temp, t_token::cmds, copy_array(), t_token::data, t_token::error, ft_free_split(), and join_split().
Referenced by clean_cmd().
join_envp()
int join_envp (t_token * token, t_clean * clean, char ** temp, int i)
Definition at line 121 of file parse6b_clean_name_join_envp.c.
References add_array(), t_clean::envp_temp, t_token::error, t_clean::file, ft_cmd(), is_space(), join_envp_1(), t_clean::new, and t_clean::temp.
Referenced by check_split_envp().
join_envp_char()
int join_envp_char (t_token * token, t_clean * clean, char * str)
Definition at line 59 of file parse6b_clean_name_join_envp.c.
References add_array(), t_token::error, ft_charjoin(), ft_free_split(), t_clean::new_array, and t_clean::temp.
Referenced by clean_name_char().
join_envp_str()
int join_envp_str (t_token * token, t_clean * clean, char * str)
Definition at line 32 of file parse6b_clean_name_join_envp.c.
References add_array(), t_token::error, ft_free_split(), ft_strjoin(), t_clean::new_array, and t_clean::temp.
Referenced by check_split_envp().
join_split()
char ** join_split (char *** old, char *** cmd, int i, int j)
Joins to arrays of strings together.
Concatenates two string arrays and frees the originals. The result will be allocated with malloc(). The main logic for the concatenation is in join_split2().
Parameters
old Array to concatenate on
cmd Array to concatenate with
i Counter variable, ALWAYS SET TO 0!
j Counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Concatenated array
join_split2
Author
kfan
Definition at line 69 of file utils_join.c.
References join_split2().
Referenced by ft_cmd(), join_cmd_1(), join_cmd_2(), and join_envp_1().
last_input()
int last_input (t_cmds * cmds, t_token * token)
Definition at line 107 of file pipex_input.c.
References check_builtins(), child(), t_cmds::cmd, t_token::envp, get_path(), parent(), and t_cmds::pid.
Referenced by pipex().
make_cmd_list()
int make_cmd_list (char ** temp, t_token * token)
Makes a command list of all split pipes.
Makes a command list of all split pipes. It splits the commands by redirection operators (<, <<, >>, >) and scans all pipes. Also takes one array.
Author
kfan
Parameters
temp mystery array
token token to split the commands of
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 162 of file parse3_make_cmd_list.c.
References t_cmds::cmd, t_token::cmds, scan_pipe(), and split_cmd().
Referenced by split_pipe().
make_tree()
void make_tree (t_data * data)
Creates the tree of tokens to be processed.
Splits the input string into an array of tokens to be processed and starts the execution. The string is split on the following delimiters:
;
&&
|| STDIN and STDOUT are cached for easy recovery after each call to pipex. If data->error is not 0, it will not execute the token.
Author
kfan
Parameters
data data to parse into the tokens
Definition at line 193 of file parse1_make_tree.c.
References close_unused_fd(), execute(), ft_free_split(), ft_free_token(), ft_split_delimiter(), init_tree(), make_token(), restore_fd(), and t_data::str.
Referenced by main().
mini_error()
void mini_error (char * str, char * arg, t_token * token, int * fd)
Indicates a mini error.
This function indicates a mini error in the token that is currently being processed and will not stop the processing of this token.
Author
kfan
Parameters
str message printed
token token in which the error occurred
Definition at line 33 of file error_mini.c.
References t_token::exit_code, and ft_strlen().
Referenced by clean_infile(), clean_outfile(), and execve_error().
open_error()
void open_error (char * str, t_token * token, int * fd, int k)
Indicates an open error.
This function indicates an open error in the token that is currently being processed and stops the processing of this token.
Author
kfan
Parameters
str debug feature, unused
token token in which the error occurred.
Definition at line 128 of file error_mini.c.
References t_token::cmds, t_cmds::exit_code, and ft_strlen().
Referenced by ft_heredoc(), ft_redir_in1(), infile(), and outfile().
outfile()
int outfile (t_token * token, int k)
Definition at line 17 of file pipex.c.
References t_token::cmds, t_token::exit_code, t_cmds::fd, open_error(), t_cmds::outfile, and t_cmds::redir.
Referenced by ft_free_struct(), ft_redir_out(), and open_fd().
pipex()
int pipex (t_token * token)
Definition at line 84 of file pipex.c.
References t_cmds::cmd, t_token::cmds, t_token::error, t_cmds::fd, input(), last_input(), open_fd(), and replace_fd().
Referenced by execute().
print_array()
void print_array (char ** temp)
Debug function to print an array of strings.
Debug function to print an array of strings.
Parameters
temp String array to print
Author
kfan
Definition at line 170 of file utils_array1.c.
References ft_printf().
Referenced by builtins_env(), and builtins_export().
print_token()
void print_token (t_token ** token)
redir()
int redir (char * temp, t_token * token, int k)
Check token syntax for redirections.
Check the kind of syntax in the token, check if it is valid (file name followed by a redirection operator), strdup the raw filename and put them to process.
Author
kfan
Parameters
temp foo
token command token
k foo
Returns
int
Return values
success Returns 0 on success, -1 otherwise.
Definition at line 161 of file parse4_redir.c.
References t_token::cmds, t_cmds::fd, ft_redir_in(), ft_redir_out(), ft_strdup(), is_space(), is_sym(), sym_count(), and syntax_error().
Referenced by scan_pipe().
remove_array()
char ** remove_array (char ** input, int index, int y, int j)
Duplicate an array without the value at a given index.
Duplucates an array of strings, except for the value at a given index. The excluded value will be replaced with NULL in the copy.
Parameters
input array to copy
index index of value to exclude
y counter variable, ALWAYS SET TO 0!
j counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Copied array
Author
kfan
Definition at line 131 of file utils_array2.c.
References free_if_failed(), ft_strdup(), and input().
Referenced by add_envp(), builtins_unset(), join_envp_1(), and unset_export().
restore_fd()
void restore_fd (t_data * data, int * fd)
Definition at line 118 of file utils.c.
References t_data::fd, and ft_printf().
Referenced by execute(), and make_tree().
shift_array()
void shift_array (char ** array, int length)
Shifts an array of strings to the left by one position.
All elements should be malloc'd, the first element will get freed and overwritten!
Parameters
array array to shift
length length of the array
Author
kmautner
Definition at line 53 of file utils_history.c.
Referenced by history_add().
signal_init()
int signal_init (void)
Initlialisation function for the signal handling.
This function initialises all static data required for the signal handling. Captured signals are:
SIGINT
SIGQUIT
SIGSEGV (easter egg)
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kmautner
Definition at line 72 of file signals1.c.
References error(), ft_bzero(), and signal_handler().
Referenced by end_of_file(), execute(), init_main(), and read_input().
signal_init1()
int signal_init1 (void)
Initialiser for the modified signal handlers.
Inistialiser to overwrite the standard signal handlers with the modified ones for after heredoc returns NULL.
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kfan
Definition at line 129 of file signals1.c.
References error(), ft_bzero(), and signal_handler1().
Referenced by execute(), and stop_heredoc().
signal_init_execve()
int signal_init_execve (void)
Initialises the execve signal handler.
Initialises the modified signal handler for execve.
Returns
int
Return values
success 0 on success, 1 otherwise.
signal_init
Author
kfan
Definition at line 103 of file signals2.c.
References error(), ft_bzero(), and signal_handler_execve().
Referenced by execute().
signal_init_here_doc()
int signal_init_here_doc (void)
Initialiser for the modified signal handlers.
Inistialiser to overwrite the standard signal handlers with the modified ones for heredoc.
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kfan
Definition at line 51 of file signals2.c.
References error(), ft_bzero(), and signal_handler_here_doc().
Referenced by ft_heredoc().
signal_init_post_execve()
int signal_init_post_execve (void)
Initialiser for the modified signal handlers.
For waitpid in parent to ignore all signals, eg. ./minishell
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kfan
Definition at line 129 of file signals2.c.
References error().
Referenced by wait_pipes().
small_free()
void small_free (t_token ** token, int i)
Small version of ft_free_token()
Call this instead of ft_free_token() when the malloc() inside ft_init_token() fails!
Parameters
token token to free
i size of the token data
t_token init_token ft_free_token
Author
kfan
Definition at line 129 of file utils_free.c.
Referenced by init_token().
sort_array()
void sort_array (char ** input)
Sorts an array of strings.
Sorts an array of strings by their ASCII value. The sorting happens in place!
Parameters
input array to sort
Author
kfan
Definition at line 26 of file utils_array1.c.
References ft_strlen(), ft_strncmp(), and input().
Referenced by add_envp_export(), and init_main().
sort_array_wildcards()
void sort_array_wildcards (char ** input)
Definition at line 94 of file utils_array1.c.
References ft_strlen(), ft_strncmp_alpha(), and input().
Referenced by wildcards().
str_equals()
int str_equals (char * str1, char * str2)
Checks if two strings are equal.
This function checks if two strings are equal. They are equal if:
They have the same length
They have the same characters in the same positions
Parameters
str1 first string
str2 second string
Returns
int
Return values
success 0 if the strings are equal, 1 otherwise.
Author
kmautner
Definition at line 30 of file utils_history.c.
References ft_strlen(), and ft_strncmp().
Referenced by builtins_cd(), builtins_env(), builtins_exit(), builtins_export(), builtins_pipe_fd_in(), builtins_pipe_fd_out(), builtins_pwd(), builtins_unset(), check_and_change_path(), check_builtins(), exit_arg(), and history_add().
sym_count()
int sym_count (char c1, char c2, char * pin)
Definition at line 36 of file utils_count.c.
References name_count().
Referenced by ft_count(), ft_count(), ft_newstring(), ft_newstring(), and redir().
syntax_error()
void syntax_error (char * str, t_token * token)
Indicates a syntax error.
This function indicates a syntax error in the token that is currently being processed and stops the processing of this token.
Author
kfan
Parameters
str message printed
token token in which the error occurred
Definition at line 32 of file error.c.
References t_token::error, t_token::exit_code, and ft_strlen().
Referenced by check_cmd(), check_temp(), clean_infile(), clean_name(), clean_name_no_expand(), clean_outfile(), and redir().
wait_pipes()
void wait_pipes (t_token * token, int i, int status)
Definition at line 106 of file pipex_utils.c.
References t_token::cmds, t_token::error, t_cmds::exit_code, t_token::exit_code, g_sigrecv, t_cmds::pid, and signal_init_post_execve().
Referenced by execute().
warn()
void warn (char * msg)
Prints a warning to stdout.
This function prints a warning message to the standard output (fd = 1). All messages are prepended with "\033[1;43m WARNING \033[22;0m -> " and terminated with a newline.
Author
kmautner
Parameters
msg message to print, may be NULL
Definition at line 90 of file error.c.
References ft_strlen().
Referenced by init_history(), and read_history_file().
wildcards()
char * wildcards (char * temp, t_token * token, t_clean * clean)
Definition at line 140 of file parse8_wildcards.c.
References clean_name(), ft_calloc(), ft_strdup(), get_files(), sort_array_wildcards(), t_clean::temp, and t_token::wildcards.
Referenced by clean_name_char().
Variable Documentation
g_sigrecv
int g_sigrecv extern
Definition at line 26 of file signals1.c.
Referenced by read_input(), signal_handler(), signal_handler1(), signal_handler_execve(), signal_handler_here_doc(), stop_heredoc(), and wait_pipes().