Minishell: parse4a_redir_heredoc.c File Reference
parse4a_redir_heredoc.c File Reference
#include "minishell.h"
Functions
static int stop_heredoc (t_token *token, int fd, int fd_temp)
Stop the heredoc interpretation.
static char * expand_heredoc (char *temp, t_token *token, char *temp_expanded, int i)
Expand envp in heredocs.
static void end_of_file (char *temp, int fd_temp)
Found eof.
static int write_heredoc (t_token *token, int fd, char *eof, int quote)
Main heredoc functionality.
int ft_heredoc (t_token *token, char *eof, char *file, int k)
Handles the functionality of a heredoc.
Function Documentation
end_of_file()
static void end_of_file (char * temp, int fd_temp) static
Found eof.
Function to call when eof has been found in the heredoc to clean up after.
Author
kfan
Parameters
temp heredoc content
fd_temp heredoc file descriptor
Definition at line 110 of file parse4a_redir_heredoc.c.
References signal_init().
Referenced by write_heredoc().
expand_heredoc()
static char * expand_heredoc (char * temp, t_token * token, char * temp_expanded, int i) static
Expand envp in heredocs.
Expand environment variables inside of a heredoc by looping through every character in temp to find a $-prefixed identifier to expand with the environment variable of the same name.
During execution, temp will be overwritten with the expanded heredoc data, which is also returned by the function.
Author
kfan
Parameters
temp[in,out] heredoc data
token[in] command token
temp_expanded expanded temp (Always set to NULL!)
i counter variable (Always set to 0!)
Returns
char*
Return values
temp Expanded version of temp.
Definition at line 70 of file parse4a_redir_heredoc.c.
References check_envp_count(), expand_envp(), free_heredoc(), ft_strjoin(), ft_strlen(), and ft_substr().
Referenced by write_heredoc().
ft_heredoc()
int ft_heredoc (t_token * token, char * eof, char * file, int k)
Handles the functionality of a heredoc.
Creates a temporary file for the user to write to when using a heredoc and deletes it afterwards.
Author
kfan
Parameters
token Command token
eof End of file indicator
Returns
int
Return values
fd File descriptor of the heredoc.
Definition at line 176 of file parse4a_redir_heredoc.c.
References is_quote(), open_error(), signal_init_here_doc(), and write_heredoc().
Referenced by ft_redir_in1().
stop_heredoc()
static int stop_heredoc (t_token * token, int fd, int fd_temp) static
Stop the heredoc interpretation.
Stop the heredoc if the heredoc readline returns NULL, which means it received either SIGINT (CTRL + C) or SIGQUIT (CTRL + D).
If the heredoc in unexpectedly terminated (reached the end of file), a warning is printed to stdout (fd = 2).
Author
kfan
Parameters
token[in] command token
fd[in] File descriptor to terminate
fd_temp[in] Heredoc file dexcriptor
Returns
int
Return values
success Returns 0 on success or 1 on error.
Definition at line 32 of file parse4a_redir_heredoc.c.
References t_token::data, t_token::error, t_token::exit_code, g_sigrecv, t_data::readline_switch, and signal_init1().
Referenced by write_heredoc().
write_heredoc()
static int write_heredoc (t_token * token, int fd, char * eof, int quote) static
Main heredoc functionality.
Handles the bulk of the heredoc funcitonality, allowing the user to write into a temporary file to get more complex input for a command. Environment variables referenced inside of the heredoc are expanded before passing it to execution.
Author
kfan
Parameters
token command token
temp buffer to read into (unused as argument)
fd file descriptor of the heredoc file
eof end of file character(s)
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 136 of file parse4a_redir_heredoc.c.
References end_of_file(), expand_heredoc(), ft_strlen(), ft_strncmp(), and stop_heredoc().
Referenced by ft_heredoc().