Minishell: parse7_expand_envp.c File Reference
parse7_expand_envp.c File Reference
#include "minishell.h"
Functions
int check_envp_count (char *temp)
static int check_sys_envp_count (char *temp)
static char * expand_exit_code (t_token *token, char *new)
char * expand_envp (char *temp, t_token *token, char *new, int quote)
Function Documentation
check_envp_count()
int check_envp_count (char * temp)
Definition at line 16 of file parse7_expand_envp.c.
References ft_isalnum().
Referenced by clean_name_envp(), expand_envp(), and expand_heredoc().
check_sys_envp_count()
static int check_sys_envp_count (char * temp) static
Definition at line 28 of file parse7_expand_envp.c.
Referenced by expand_envp().
expand_envp()
char * expand_envp (char * temp, t_token * token, char * new, int quote)
Definition at line 52 of file parse7_expand_envp.c.
References check_envp_count(), check_sys_envp_count(), t_token::envp, expand_exit_code(), ft_calloc(), ft_isalpha(), ft_strdup(), ft_strncmp(), and is_quote().
Referenced by clean_name_envp(), and expand_heredoc().
expand_exit_code()
static char * expand_exit_code (t_token * token, char * new) static
Definition at line 42 of file parse7_expand_envp.c.
References t_token::exit_code, ft_itoa(), and ft_printf().
Referenced by expand_envp().