Minishell: parse6b_clean_name_join_envp.c File Reference
parse6b_clean_name_join_envp.c File Reference
#include "minishell.h"
Functions
void check_new_array (t_clean *clean)
int join_envp_str (t_token *token, t_clean *clean, char *str)
int join_envp_char (t_token *token, t_clean *clean, char *str)
static void join_envp_1 (t_clean *clean, char **temp, int j, char *str)
int join_envp (t_token *token, t_clean *clean, char **temp, int i)
Function Documentation
check_new_array()
void check_new_array (t_clean * clean)
Definition at line 16 of file parse6b_clean_name_join_envp.c.
References t_clean::envp_temp, is_space(), and t_clean::new_array.
Referenced by check_split_envp().
join_envp()
int join_envp (t_token * token, t_clean * clean, char ** temp, int i)
Definition at line 121 of file parse6b_clean_name_join_envp.c.
References add_array(), t_clean::envp_temp, t_token::error, t_clean::file, ft_cmd(), is_space(), join_envp_1(), t_clean::new, and t_clean::temp.
Referenced by check_split_envp().
join_envp_1()
static void join_envp_1 (t_clean * clean, char ** temp, int j, char * str) static
Definition at line 90 of file parse6b_clean_name_join_envp.c.
References copy_array(), ft_strjoin(), join_split(), remove_array(), and t_clean::temp.
Referenced by join_envp().
join_envp_char()
int join_envp_char (t_token * token, t_clean * clean, char * str)
Definition at line 59 of file parse6b_clean_name_join_envp.c.
References add_array(), t_token::error, ft_charjoin(), ft_free_split(), t_clean::new_array, and t_clean::temp.
Referenced by clean_name_char().
join_envp_str()
int join_envp_str (t_token * token, t_clean * clean, char * str)
Definition at line 32 of file parse6b_clean_name_join_envp.c.
References add_array(), t_token::error, ft_free_split(), ft_strjoin(), t_clean::new_array, and t_clean::temp.
Referenced by check_split_envp().