Minishell: parse5_clean_and_expand.c File Reference
parse5_clean_and_expand.c File Reference
#include "minishell.h"
Functions
static int clean_cmd (t_token *token, char *file, int i, int j)
Clean and expand commands.
static int clean_cmd_list (t_token *token)
Clean and expand all commands.
static int clean_outfile (t_token *token)
Lorem Ipsum.
static int clean_infile (t_token *token)
Lorem Ipsum.
int clean_and_expand (t_token *token)
Clean and expand all tokens.
Function Documentation
clean_and_expand()
int clean_and_expand (t_token * token)
Clean and expand all tokens.
Clean and expand all commands, infiles and outfiles inside of all pipes in the list of tokens.
Author
kfan
Parameters
token List of tokens
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 178 of file parse5_clean_and_expand.c.
References clean_cmd_list(), clean_infile(), and clean_outfile().
Referenced by execute().
clean_cmd()
static int clean_cmd (t_token * token, char * file, int i, int j) static
Clean and expand commands.
Clean up and expand the command list inside of a pipe. join_cmd_1 for envp split > 1 (or wildcards) join_cmd_2 for envp i = 0 to wipe the current array fo strings and skip
Author
kfan
Parameters
token command token
file NULL
i start index
j -1
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 31 of file parse5_clean_and_expand.c.
References clean_name(), t_cmds::cmd, t_data::cmd_temp, t_token::cmds, t_token::data, t_token::error, ft_calloc(), ft_free_split(), join_cmd_1(), join_cmd_2(), and t_token::wildcards.
Referenced by clean_cmd_list().
clean_cmd_list()
static int clean_cmd_list (t_token * token) static
Clean and expand all commands.
Cleans and expands all the commands in all pipes inside the list of tokens.
Author
kfan
Parameters
token command token
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 72 of file parse5_clean_and_expand.c.
References clean_cmd(), and t_token::cmds.
Referenced by clean_and_expand().
clean_infile()
static int clean_infile (t_token * token) static
Lorem Ipsum.
Lorem Ipsum Dolor Si Amet
Author
kfan
Parameters
token command token
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 137 of file parse5_clean_and_expand.c.
References clean_name(), t_token::cmds, t_cmds::fd, ft_calloc(), ft_printf(), t_cmds::infile, mini_error(), syntax_error(), and t_token::wildcards.
Referenced by clean_and_expand().
clean_outfile()
static int clean_outfile (t_token * token) static
Lorem Ipsum.
Lorem Ipsum Dolor Si Amet
Author
kfan
Parameters
token command token
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 97 of file parse5_clean_and_expand.c.
References clean_name(), t_token::cmds, t_cmds::fd, ft_calloc(), ft_printf(), mini_error(), t_cmds::outfile, syntax_error(), and t_token::wildcards.
Referenced by clean_and_expand().