Minishell: parse1_make_tree.c File Reference
parse1_make_tree.c File Reference
#include "minishell.h"
Functions
static int check_temp (char **temp, int error_count, int k)
Check for errors and count the amount of token arrays needed.
static t_token ** make_token (char **temp, t_token **token, t_data *data)
Creates a token.
static int execute (t_token **token, t_data *data, int *fd, int i)
Executes tokens.
static int init_tree (t_data *data, int *fd)
Initializes the data for token processing.
void make_tree (t_data *data)
Creates the tree of tokens to be processed.
Function Documentation
check_temp()
static int check_temp (char ** temp, int error_count, int k) static
Check for errors and count the amount of token arrays needed.
It will throw error if two delimiters are next to each other (eg: "; ;" or "; &&" or "|| &&") error_count starts at 0 and will increment whenever it hits a delimiter. If it hits a non-delimiter it resets and it throws an error when it goes over 1.
Author
kfan
Parameters
temp array of split of the initial str
error_count Counting variable (always set to 0!)
Returns
int
Return values
amount Number of arrays needed for malloc the **token.
Definition at line 31 of file parse1_make_tree.c.
References is_delimiter(), is_space(), and syntax_error().
Referenced by make_token().
execute()
static int execute (t_token ** token, t_data * data, int * fd, int i) static
Executes tokens.
This function executes a list of tokens. This function is also a breaking point for execution, should something go wrong inside it. new: reset fd after all pipe, technically force update fd new: wait here instead of in pipex parent
Author
kfan
Parameters
token Array of tokens to execute
data Data struct containing needed information
fd Array od duplicated file descriptors
i Just a counter starting with 0
Returns
int
Return values
success Always returns 0.
Definition at line 110 of file parse1_make_tree.c.
References clean_and_expand(), t_data::envp, t_token::envp, t_data::envp_export, t_token::envp_export, t_data::error, pipex(), t_data::readline_switch, restore_fd(), signal_init(), signal_init1(), signal_init_execve(), and wait_pipes().
Referenced by make_tree().
init_tree()
static int init_tree (t_data * data, int * fd) static
Initializes the data for token processing.
This function initializes the tree creation process. It duplicates STDIN and STDOUT using dup() and writes them into fd[0] and fd[1] respectively.
Author
kfan
Parameters
data pointer to data struct
fd pointer to duplicate file descriptors into
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 151 of file parse1_make_tree.c.
References t_data::cmd_temp, t_data::error, t_data::fd, t_data::fd_in, and t_data::fd_out.
Referenced by make_tree().
make_token()
static t_token ** make_token (char ** temp, t_token ** token, t_data * data) static
Creates a token.
Creates an array of token structs and initialises them with the commands inside temp and the data inside data
Author
kfan
Parameters
temp command list
token Array of tokens
data data struct pointer
Returns
t_token**
Return values
token New token or NULL on error.
Definition at line 75 of file parse1_make_tree.c.
References check_temp(), t_data::error, t_data::exit_code, and init_token().
Referenced by make_tree().
make_tree()
void make_tree (t_data * data)
Creates the tree of tokens to be processed.
Splits the input string into an array of tokens to be processed and starts the execution. The string is split on the following delimiters:
;
&&
|| STDIN and STDOUT are cached for easy recovery after each call to pipex. If data->error is not 0, it will not execute the token.
Author
kfan
Parameters
data data to parse into the tokens
Definition at line 187 of file parse1_make_tree.c.
References close_unused_fd(), execute(), ft_free_split(), ft_free_token(), ft_split_delimiter(), init_tree(), make_token(), restore_fd(), and t_data::str.
Referenced by main().