Minishell: parse6a_clean_name_no_expand.c File Reference
parse6a_clean_name_no_expand.c File Reference
#include "minishell.h"
Functions
int get_rid_of_extra_space (char *temp)
static int clean_name_char (char *temp, t_clean *clean)
void init_clean (t_clean *clean, int count, char *file)
char * clean_name_no_expand (char *temp, t_token *token, int count, char *file)
Function Documentation
clean_name_char()
static int clean_name_char (char * temp, t_clean * clean) static
Definition at line 33 of file parse6a_clean_name_no_expand.c.
References t_clean::count, t_clean::file, ft_charjoin(), ft_strdup(), get_rid_of_extra_space(), is_quote(), is_space(), t_clean::new, t_clean::quote, and t_clean::space.
Referenced by clean_name_no_expand().
clean_name_no_expand()
char * clean_name_no_expand (char * temp, t_token * token, int count, char * file)
Definition at line 66 of file parse6a_clean_name_no_expand.c.
References clean_name_char(), t_clean::count, t_clean::file, init_clean(), inside_quote(), is_space(), t_clean::new, t_clean::quote, and syntax_error().
Referenced by ft_redir_in1().
get_rid_of_extra_space()
int get_rid_of_extra_space (char * temp)
Definition at line 18 of file parse6a_clean_name_no_expand.c.
References is_space().
Referenced by clean_name_char(), and clean_name_char().
init_clean()
void init_clean (t_clean * clean, int count, char * file)
Definition at line 52 of file parse6a_clean_name_no_expand.c.
References t_clean::count, t_clean::envp_temp, t_clean::file, t_clean::new, t_clean::new_array, t_clean::quote, t_clean::space, and t_clean::temp.
Referenced by clean_name(), and clean_name_no_expand().