Minishell: parse8_wildcards.c File Reference
parse8_wildcards.c File Reference
#include "minishell.h"
Functions
static int find_star (char *temp)
static int filter_prefix (char *temp, char *input, int i, int index)
static int filter (char *temp, char *input)
static char ** get_files (char *temp, char **array)
char * wildcards (char *temp, t_token *token, t_clean *clean)
Function Documentation
filter()
static int filter (char * temp, char * input) static
Definition at line 86 of file parse8_wildcards.c.
References filter_prefix(), find_star(), ft_strlen(), and input().
Referenced by get_files().
filter_prefix()
static int filter_prefix (char * temp, char * input, int i, int index) static
Definition at line 53 of file parse8_wildcards.c.
References ft_strlen(), ft_strncmp(), ft_strnstr(), ft_substr(), and input().
Referenced by filter().
find_star()
static int find_star (char * temp) static
Definition at line 24 of file parse8_wildcards.c.
References inside_quote().
Referenced by filter().
get_files()
static char ** get_files (char * temp, char ** array) static
Definition at line 107 of file parse8_wildcards.c.
References add_array(), filter(), and ft_free_split().
Referenced by wildcards().
wildcards()
char * wildcards (char * temp, t_token * token, t_clean * clean)
Definition at line 140 of file parse8_wildcards.c.
References clean_name(), ft_calloc(), ft_strdup(), get_files(), sort_array_wildcards(), t_clean::temp, and t_token::wildcards.
Referenced by clean_name_char().