Minishell: parse3_make_cmd_list.c File Reference
parse3_make_cmd_list.c File Reference
#include "minishell.h"
Functions
char ** ft_cmd (char *temp, t_token *token, char **old)
Splits the command and separates them with spaces.
static int scan_pipe (char **temp, t_token *token, int k, char **cmd)
Scans the command for pipes.
static int split_cmd (t_token *token, char **temp)
Make a command list of all split pipes.
int make_cmd_list (char **temp, t_token *token)
Makes a command list of all split pipes.
Function Documentation
ft_cmd()
char ** ft_cmd (char * temp, t_token * token, char ** old)
Splits the command and separates them with spaces.
Split the temp cmd with a modified split to seperate the cmd and arg with space. Space inside a quote will not be skipped! Quotes and $ are still inside yet and will be cleaned and expanded later. Join the new split with previous split.
Example: "<infile echo >out 'hel lo' world$USER" will become:
echo
'hel lo'
world$USER
Author
kfan
Parameters
temp command to split
token token
old old split
Returns
char**
Return values
cmd Returns old, or NULL on error.
Definition at line 38 of file parse3_make_cmd_list.c.
References t_token::error, ft_split_space(), and join_split().
Referenced by join_envp(), and scan_pipe().
make_cmd_list()
int make_cmd_list (char ** temp, t_token * token)
Makes a command list of all split pipes.
Makes a command list of all split pipes. It splits the commands by redirection operators (<, <<, >>, >) and scans all pipes. Also takes one array.
Author
kfan
Parameters
temp mystery array
token token to split the commands of
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 162 of file parse3_make_cmd_list.c.
References t_cmds::cmd, t_token::cmds, scan_pipe(), and split_cmd().
Referenced by split_pipe().
scan_pipe()
static int scan_pipe (char ** temp, t_token * token, int k, char ** cmd) static
Scans the command for pipes.
Scans the command array in temp for pipes. If the array starts with a redirection syntax, a redirection is done. Otherwise it will go through ft_cmd(). If the syntax is only valid with the context of a pipe it just returns 0. Frees and replaces token->cmds[k]->cmd with the parsed **cmd.
Author
kfan
Parameters
temp cmd list with redir syntax
token struct to parse command into
k mystery integer
cmd parsed command
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 79 of file parse3_make_cmd_list.c.
References t_cmds::cmd, t_token::cmds, t_token::error, ft_cmd(), ft_free_split(), is_space(), is_sym(), and redir().
Referenced by make_cmd_list().
split_cmd()
static int split_cmd (t_token * token, char ** temp) static
Make a command list of all split pipes.
This functions makes a command list of all split pipes. It will skip an array if the array is a pipe '|'. The commands are also split by redirection operators (<, <<, >>, >). Also takes one array.
Author
kfan
Parameters
token token to split the commands of
temp mystery array
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 122 of file parse3_make_cmd_list.c.
References t_cmds::cmd, t_token::cmds, t_token::error, ft_split_cmd(), and is_pipe().
Referenced by make_cmd_list().