Minishell: parse6_clean_name.c File Reference
parse6_clean_name.c File Reference
#include "minishell.h"
Functions
static int check_split_envp (t_token *token, t_clean *clean, int i)
Check if a command is valid after expanding variables.
static int clean_name_envp (char *temp, t_token *token, t_clean *clean)
Expand envp.
static int clean_name_char (char *temp, t_token *token, t_clean *clean)
Clean up a command.
static int loop_str (char *temp, t_token *token, t_clean *clean)
Clean and expand a string.
char * clean_name (char *temp, t_token *token, int count, char *file)
Expand input.
Function Documentation
check_split_envp()
static int check_split_envp (t_token * token, t_clean * clean, int i) static
Check if a command is valid after expanding variables.
Check if there is valid space with split after envp is expanded. Eg.: export STH="echo 123"; $STH. If i == 1, just dup check[0] replace.
Author
kfan
Parameters
token command token
clean clean struct
i counter variable (Always set to 0!)
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 30 of file parse6_clean_name.c.
References check_new_array(), t_clean::envp_temp, t_clean::file, ft_free_split(), ft_split_space(), ft_strjoin(), ft_strncmp(), join_envp(), join_envp_str(), t_clean::new, t_clean::new_array, t_clean::quote, t_clean::temp, and t_token::wildcards.
Referenced by clean_name_envp().
clean_name()
char * clean_name (char * temp, t_token * token, int count, char * file)
Expand input.
Expand environment variables in temp. Environment variables inside '' (single quotes) should not be expanded, otherwise they should always expand. Any extra space outside of quotes should be removed. count == 0 for cmd, otherwise for redir. Only create new cmd array if token->pipe == 0 ???
Author
kfan
Parameters
temp string to expand
token command token
count start index
file foo
Returns
char*
Return values
new clean.new on success, NULL otherwise.
Definition at line 218 of file parse6_clean_name.c.
References t_data::cmd_temp, t_token::data, ft_strdup(), init_clean(), is_space(), loop_str(), t_clean::new, t_clean::quote, syntax_error(), t_clean::temp, and t_token::wildcards.
Referenced by clean_cmd(), clean_infile(), clean_outfile(), ft_redir_in1(), ft_redir_out(), and wildcards().
clean_name_char()
static int clean_name_char (char * temp, t_token * token, t_clean * clean) static
Clean up a command.
Clean up a command. New: WIldcards! Wildcards only expand if they're not in a quote (quote == 0). temp[clean->count] = current character. Get rid of excess space to check character by character and only join the new character if it is not an extra space. Filter out the quotes and extra space by strdup. Space inside quotes will not be filtered out. clean->quote indicates the current status of being inside a quote or not. If quote > 0 the current position is inside a quote. If quote > 2 the current position is inside a quote witin a quote, which the quote will be copied. Eg.: "'$USER'" or '"$USER"'. if space < 2 wild_switch == 0; jackpot no hit, you only have one chance to verify after you hit it. New: if (clean->envp_temp) join the character at the end of the array.
Author
kfan
Parameters
temp
token command token
clean clean struct
Returns
int
Return values
success Returns 0 on success, -1 on error.
Definition at line 133 of file parse6_clean_name.c.
References t_clean::count, t_clean::file, ft_charjoin(), ft_strdup(), ft_strncmp(), get_rid_of_extra_space(), is_quote(), is_space(), join_envp_char(), t_clean::new, t_clean::quote, t_clean::space, t_clean::temp, t_token::wildcards, and wildcards().
Referenced by loop_str().
clean_name_envp()
static int clean_name_envp (char * temp, t_token * token, t_clean * clean) static
Expand envp.
Check the character count of envp for temp to skip index. Reset space counter to 0. Join the previously processed string with the new, expanded envp. Check envp with ft_split_space if envp has spaces in between entries. If yes and i > 1 it means ther's spaces inbetween and it will allocate clean->temp for later proccessing. --—important: if i = 0 for later wiping out of the current array of str --—important: COnditions: only applies if it's the first char that's valid or not inside "" (double quotes). --—and together if there's sth in the previous process str. If clean->temp exists, it will later in clean_cmd being process with join_cmd and wipe the clean->new created string.
Author
kfan
Parameters
temp
token
clean
Returns
int
Return values
success Returns 0 on success, -1 on error.
Definition at line 83 of file parse6_clean_name.c.
References check_envp_count(), check_split_envp(), t_clean::count, t_clean::envp_temp, t_token::error, expand_envp(), t_clean::file, ft_strjoin(), ft_strlen(), t_clean::new, t_clean::quote, and t_clean::space.
Referenced by loop_str().
loop_str()
static int loop_str (char * temp, t_token * token, t_clean * clean) static
Clean and expand a string.
Loop through the string temp to remove quotes, expand environment variables and expand wildcards.
Author
kfan
Parameters
temp string to expand
token command token
clean clean struct
Returns
int
Return values
success Returns 0 on success, 1 on error.
Definition at line 176 of file parse6_clean_name.c.
References clean_name_char(), clean_name_envp(), t_clean::count, t_clean::file, inside_quote(), t_clean::new, and t_clean::quote.
Referenced by clean_name().