Minishell: parse4_redir.c File Reference
parse4_redir.c File Reference
#include "minishell.h"
Functions
<<<<<<< HEAD=======> > > > > > static int ft_redir_in1 (t_token *token, int type, char *new, int k)
2nd part of ft_redir_in()
static int ft_redir_in (t_token *token, int type, char *file, int k)
Redirect input.
static void ft_redir_out (t_token *token, int type, char *file, int k)
redirect output
int redir (char *temp, t_token *token, int k)
Check token syntax for redirections.
Function Documentation
ft_redir_in()
static int ft_redir_in (t_token * token, int type, char * file, int k) static
Redirect input.
Free the previous filename if a new input file exists within the same pipe and close fd if the previous syntax is a heredoc. calloc and clean the name later, no expand for heredoc. No expansions of $USER for eof, only quites and space at the end.
Author
kfan
Parameters
token command token
type foo
file path to infile
k foo
Returns
int
Return values
success Returns 0 on success, -1 otherwise.
Definition at line 85 of file parse4_redir.c.
References t_token::cmds, t_token::data, t_cmds::fd, t_data::fd, ft_calloc(), ft_redir_in1(), t_cmds::infile, and t_cmds::redir.
Referenced by redir().
ft_redir_in1()
<<<<<<< HEAD======= > > > > > > static int ft_redir_in1 (t_token * token, int type, char * new, int k) static
2nd part of ft_redir_in()
Check if the input is a heredoc or a regular infile. Clean the name, no expand for heredoc. Check if the file can be opened.
Author
kfan
Parameters
token command token
type foo
new path to the infile
k foo
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 39 of file parse4_redir.c.
References clean_name(), clean_name_no_expand(), t_token::cmds, t_cmds::fd, ft_heredoc(), t_cmds::infile, open_error(), and t_cmds::redir.
Referenced by ft_redir_in().
ft_redir_out()
static void ft_redir_out (t_token * token, int type, char * file, int k) static
redirect output
Free the previous filename if a new output file exists within the same pipe, parsing the type into the token struct. calloc and clean the name, then create and truncate the file if necessary. Put the outfile name back to the raw name for later processing before pipex because of splitting and wildcards.
Author
kfan
Parameters
token command token
type foo
file path to output
k foo
Definition at line 121 of file parse4_redir.c.
References clean_name(), t_token::cmds, ft_calloc(), t_cmds::outfile, outfile(), and t_cmds::redir.
Referenced by redir().
redir()
int redir (char * temp, t_token * token, int k)
Check token syntax for redirections.
Check the kind of syntax in the token, check if it is valid (file name followed by a redirection operator), strdup the raw filename and put them to process.
Author
kfan
Parameters
temp foo
token command token
k foo
Returns
int
Return values
success Returns 0 on success, -1 otherwise.
Definition at line 161 of file parse4_redir.c.
References t_token::cmds, t_cmds::fd, ft_redir_in(), ft_redir_out(), ft_strdup(), is_space(), is_sym(), sym_count(), and syntax_error().
Referenced by scan_pipe().