Minishell: parse2_init.c File Reference
parse2_init.c File Reference
#include "minishell.h"
Functions
static int check_cmd (char **temp, t_token *token, int error_count)
checks errors and arrays needed to malloc the cmds struct
static int check_and_malloc (char **temp, t_token *token, int i)
Checks, mallocs and initialises a struct.
static int split_pipe (char *cmds, t_token *token)
Split the array on pupes and check for errors.
static void init_token1 (char **temp, t_token **token)
Second part of token initialisation.
int init_token (char **temp, t_token **token, t_data *data, int i)
Initialises a token array.
Function Documentation
check_and_malloc()
static int check_and_malloc (char ** temp, t_token * token, int i) static
Checks, mallocs and initialises a struct.
Checks errors and arrays needed to malloc the cmds struct, malloc it and initilize the struct.
Author
kfan
Parameters
temp initial split
token token struct
i just a count starting with 0 to save lines
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 74 of file parse2_init.c.
References check_cmd(), t_cmds::cmd, t_token::cmds, t_token::data, t_token::error, t_cmds::exit_code, t_cmds::fd, t_data::fd, t_cmds::infile, t_token::nmb_of_cmd, t_cmds::outfile, t_cmds::pid, and t_cmds::redir.
Referenced by split_pipe().
check_cmd()
static int check_cmd (char ** temp, t_token * token, int error_count) static
checks errors and arrays needed to malloc the cmds struct
Throws error if two pipes are next to each other eg. "| |". Error_count starts at one will throw syntax error if a cmd starts with a pipe. Error_count resets to zero if it hits anything other than a pipe and increment if it hits one
Author
kfan
Parameters
temp second split of pipe
token token struct
error_count error_count
Returns
int
Return values
cmd Arrays need for the char **cmd aka token->nmb_of_cmd.
Definition at line 31 of file parse2_init.c.
References is_pipe(), is_space(), and syntax_error().
Referenced by check_and_malloc().
init_token()
int init_token (char ** temp, t_token ** token, t_data * data, int i)
Initialises a token array.
Sets the parameters taken from data in every token of a token array.
Author
kfan
Parameters
temp command list
token array of t_token structs
data t_data struct
i length of the token array
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 195 of file parse2_init.c.
References t_token::cmds, t_token::data, t_token::delimiter, t_data::envp, t_token::envp, t_data::envp_export, t_token::envp_export, t_data::error, t_token::error, t_data::exit_code, t_token::exit_code, t_data::fd_in, t_token::fd_in, t_data::fd_out, t_token::fd_out, init_token1(), t_token::nmb_of_cmd, small_free(), and t_token::wildcards.
Referenced by make_token().
init_token1()
static void init_token1 (char ** temp, t_token ** token) static
Second part of token initialisation.
It checks the initial split of the str and stores the value of the delimiter to the malloc-ed token tree for later use in bonus of just normal ; seperation of cmds (not mandatory)
token[k]->delimiter: 0 = end; 1 = ; 2 = && 3 = ||
Author
kfan
Parameters
temp initial split
token token array
Definition at line 152 of file parse2_init.c.
References t_token::delimiter, is_delimiter(), is_space(), and split_pipe().
Referenced by init_token().
split_pipe()
static int split_pipe (char * cmds, t_token * token) static
Split the array on pupes and check for errors.
Split the array by pipe '|', than check errors and arrays needed to malloc the cmds struct,
note that the modifidied split function also stores the '|' in an individual array
Author
kfan
Parameters
cmds individual str of cmd after initial split
token token struct
Returns
int
Return values
success Returns 0 on success, 1 otherwise.
Definition at line 118 of file parse2_init.c.
References check_and_malloc(), t_token::cmds, t_token::error, ft_free_split(), ft_split_pipe(), and make_cmd_list().
Referenced by init_token1().