Minishell: pipex_input.c File Reference
pipex_input.c File Reference
#include "minishell.h"
Functions
static int check_builtins (t_cmds *cmds, t_token *token, int *fd)
static void child (int *fd, t_cmds *cmds, t_token *token, char *path)
static void parent (int *fd)
int input (t_cmds *cmds, t_token *token)
int last_input (t_cmds *cmds, t_token *token)
Function Documentation
check_builtins()
static int check_builtins (t_cmds * cmds, t_token * token, int * fd) static
Definition at line 16 of file pipex_input.c.
References builtins_cd(), builtins_echo(), builtins_env(), builtins_exit(), builtins_export(), builtins_pipe_fd_in(), builtins_pipe_fd_out(), builtins_pwd(), builtins_unset(), t_cmds::cmd, t_token::envp, t_cmds::exit_code, t_token::exit_code, and str_equals().
Referenced by input(), and last_input().
child()
static void child (int * fd, t_cmds * cmds, t_token * token, char * path) static
Definition at line 45 of file pipex_input.c.
References t_cmds::cmd, t_token::envp, execve_error(), and t_cmds::outfile.
Referenced by input(), and last_input().
input()
int input (t_cmds * cmds, t_token * token)
Definition at line 78 of file pipex_input.c.
References check_builtins(), child(), t_cmds::cmd, empty_pipe(), t_token::envp, t_cmds::fd, get_path(), parent(), and t_cmds::pid.
Referenced by add_array(), copy_array(), copy_array_prefix(), filter(), filter_prefix(), ft_flags(), ft_ispercent(), ft_loop(), ft_printf(), pipex(), remove_array(), sort_array(), and sort_array_wildcards().
last_input()
int last_input (t_cmds * cmds, t_token * token)
Definition at line 108 of file pipex_input.c.
References check_builtins(), child(), t_cmds::cmd, t_token::envp, get_path(), parent(), and t_cmds::pid.
Referenced by pipex().
parent()
static void parent (int * fd) static
Definition at line 63 of file pipex_input.c.
Referenced by input(), and last_input().