Minishell: pipex.c File Reference
pipex.c File Reference
#include "minishell.h"
Functions
int outfile (t_token *token, int k)
static int infile (t_token *token, int k)
static int open_fd (t_token *token, int i)
static int replace_fd (t_token *token, int i)
int pipex (t_token *token)
Function Documentation
infile()
static int infile (t_token * token, int k) static
Definition at line 42 of file pipex.c.
References t_token::cmds, t_cmds::fd, t_cmds::infile, open_error(), and t_cmds::redir.
Referenced by ft_free_struct(), open_fd(), and print_token().
open_fd()
static int open_fd (t_token * token, int i) static
Definition at line 55 of file pipex.c.
References t_token::cmds, t_cmds::fd, t_cmds::infile, infile(), t_cmds::outfile, and outfile().
Referenced by pipex().
outfile()
int outfile (t_token * token, int k)
Definition at line 17 of file pipex.c.
References t_token::cmds, t_token::exit_code, t_cmds::fd, open_error(), t_cmds::outfile, and t_cmds::redir.
Referenced by ft_free_struct(), ft_redir_out(), open_fd(), and print_token().
pipex()
int pipex (t_token * token)
Definition at line 84 of file pipex.c.
References t_cmds::cmd, t_token::cmds, t_token::error, t_cmds::fd, input(), last_input(), open_fd(), and replace_fd().
Referenced by execute().
replace_fd()
static int replace_fd (t_token * token, int i) static
Definition at line 64 of file pipex.c.
References t_token::cmds, t_cmds::fd, t_token::fd_out, t_cmds::infile, t_token::nmb_of_cmd, and t_cmds::outfile.
Referenced by pipex().