Minishell: pipex_utils.c File Reference
pipex_utils.c File Reference
#include "minishell.h"
Functions
static void ft_free_pipex (char **array)
static char * find_bin (char **cmd, char **paths, int i)
char * get_path (char **cmd, char **envp)
int empty_pipe (int *fd)
void wait_pipes (t_token *token, int i, int status)
Function Documentation
empty_pipe()
int empty_pipe (int * fd)
Definition at line 83 of file pipex_utils.c.
Referenced by input().
find_bin()
static char * find_bin (char ** cmd, char ** paths, int i) static
Definition at line 33 of file pipex_utils.c.
References ft_strdup(), ft_strjoin(), and ft_strncmp().
Referenced by get_path().
ft_free_pipex()
static void ft_free_pipex (char ** array) static
Definition at line 15 of file pipex_utils.c.
Referenced by get_path().
get_path()
char * get_path (char ** cmd, char ** envp)
Definition at line 56 of file pipex_utils.c.
References find_bin(), ft_free_pipex(), ft_split(), ft_strdup(), and ft_strncmp().
Referenced by input(), and last_input().
wait_pipes()
void wait_pipes (t_token * token, int i, int status)
Definition at line 106 of file pipex_utils.c.
References t_token::cmds, t_token::error, t_cmds::exit_code, t_token::exit_code, g_sigrecv, t_cmds::pid, and signal_init_post_execve().
Referenced by execute().