Minishell: signals1.c File Reference
signals1.c File Reference
#include "minishell.h"
Functions
void signal_handler (int signal, siginfo_t *info, void *context)
Signal handler to process received signals.
int signal_init (void)
Initlialisation function for the signal handling.
void signal_handler1 (int signal, siginfo_t *info, void *context)
Signal handler for heredocs.
int signal_init1 (void)
Initialiser for the modified signal handlers.
Variables
int g_sigrecv
Function Documentation
signal_handler()
void signal_handler (int signal, siginfo_t * info, void * context)
Signal handler to process received signals.
This function handles signals received by minishell. The signal will be stored in sigrecv. After the signal has been processed, sigrecv should be set to 0!
Remind me to remove the easter egg when we hand it in. :P
Parameters
signal signal number
info information about the source of the signal (ignored)
context context (ignored)
Author
kmautner
Definition at line 43 of file signals1.c.
References g_sigrecv.
Referenced by signal_init().
signal_handler1()
void signal_handler1 (int signal, siginfo_t * info, void * context)
Signal handler for heredocs.
Modified version of the signal handler for after heredoc returns NULL.
Parameters
signal signal number
info signal info (ignored)
context signal context (ignored)
signal_handler
Author
kfan
Definition at line 105 of file signals1.c.
References g_sigrecv.
Referenced by signal_init1().
signal_init()
int signal_init (void)
Initlialisation function for the signal handling.
This function initialises all static data required for the signal handling. Captured signals are:
SIGINT
SIGQUIT
SIGSEGV (easter egg)
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kmautner
Definition at line 72 of file signals1.c.
References error(), ft_bzero(), and signal_handler().
Referenced by end_of_file(), execute(), and main().
signal_init1()
int signal_init1 (void)
Initialiser for the modified signal handlers.
Inistialiser to overwrite the standard signal handlers with the modified ones for after heredoc returns NULL.
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kfan
Definition at line 129 of file signals1.c.
References error(), ft_bzero(), and signal_handler1().
Referenced by execute(), and stop_heredoc().
Variable Documentation
g_sigrecv
int g_sigrecv
Definition at line 26 of file signals1.c.
Referenced by main(), signal_handler(), signal_handler1(), signal_handler_execve(), signal_handler_here_doc(), stop_heredoc(), and wait_pipes().