Minishell: signals2.c File Reference
signals2.c File Reference
#include "minishell.h"
Functions
void signal_handler_here_doc (int signal, siginfo_t *info, void *context)
Signal handler for heredocs.
int signal_init_here_doc (void)
Initialiser for the modified signal handlers.
void signal_handler_execve (int signal, siginfo_t *info, void *context)
Modified signal handler for execve.
int signal_init_execve (void)
Initialises the execve signal handler.
int signal_init_post_execve (void)
Initialiser for the modified signal handlers.
Function Documentation
signal_handler_execve()
void signal_handler_execve (int signal, siginfo_t * info, void * context)
Modified signal handler for execve.
Modified signal handler for execve because stupid.
Parameters
signal signal number
info signal info (unused)
context signal context (unused)
signal_handler
Author
kfan
Definition at line 84 of file signals2.c.
References g_sigrecv.
Referenced by signal_init_execve().
signal_handler_here_doc()
void signal_handler_here_doc (int signal, siginfo_t * info, void * context)
Signal handler for heredocs.
Modified version of the signal handler for heredocs.
Parameters
signal signal number
info signal info (ignored)
context signal context (ignored)
signal_handler
Author
kfan
Definition at line 28 of file signals2.c.
References g_sigrecv.
Referenced by signal_init_here_doc().
signal_init_execve()
int signal_init_execve (void)
Initialises the execve signal handler.
Initialises the modified signal handler for execve.
Returns
int
Return values
success 0 on success, 1 otherwise.
signal_init
Author
kfan
Definition at line 103 of file signals2.c.
References error(), ft_bzero(), and signal_handler_execve().
Referenced by execute().
signal_init_here_doc()
int signal_init_here_doc (void)
Initialiser for the modified signal handlers.
Inistialiser to overwrite the standard signal handlers with the modified ones for heredoc.
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kfan
Definition at line 51 of file signals2.c.
References error(), ft_bzero(), and signal_handler_here_doc().
Referenced by ft_heredoc().
signal_init_post_execve()
int signal_init_post_execve (void)
Initialiser for the modified signal handlers.
For waitpid in parent to ignore all signals, eg. ./minishell
Returns
int
Return values
success 0 on success, 1 otherwise.
Author
kfan
Definition at line 129 of file signals2.c.
References error().
Referenced by wait_pipes().