Minishell: utils_join.c File Reference
utils_join.c File Reference
#include "minishell.h"
Functions
static void join_split2 (char **dest, char **src, char **temp, int strlen)
Concatenating logic of join_split()
char ** join_split (char ***old, char ***cmd, int i, int j)
Joins to arrays of strings together.
int join_cmd_1 (t_token *token, int i, int j, char *file)
int join_cmd_2 (t_token *token, int i, int j, char *file)
Function Documentation
join_cmd_1()
int join_cmd_1 (t_token * token, int i, int j, char * file)
Definition at line 96 of file utils_join.c.
References t_cmds::cmd, t_data::cmd_temp, t_token::cmds, copy_array(), t_token::data, t_token::error, and join_split().
Referenced by clean_cmd().
join_cmd_2()
int join_cmd_2 (t_token * token, int i, int j, char * file)
Definition at line 123 of file utils_join.c.
References t_cmds::cmd, t_data::cmd_temp, t_token::cmds, copy_array(), t_token::data, t_token::error, ft_free_split(), and join_split().
Referenced by clean_cmd().
join_split()
char ** join_split (char *** old, char *** cmd, int i, int j)
Joins to arrays of strings together.
Concatenates two string arrays and frees the originals. The result will be allocated with malloc(). The main logic for the concatenation is in join_split2().
Parameters
old Array to concatenate on
cmd Array to concatenate with
i Counter variable, ALWAYS SET TO 0!
j Counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Concatenated array
join_split2
Author
kfan
Definition at line 69 of file utils_join.c.
References join_split2().
Referenced by ft_cmd(), join_cmd_1(), join_cmd_2(), and join_envp_1().
join_split2()
static void join_split2 (char ** dest, char ** src, char ** temp, int strlen) static
Concatenating logic of join_split()
Concatenates to arrays of strings.
Parameters
dest Array to concantenate on
src Array to concatenate with
temp Destination for resulting array
strlen Expected length of result
join_split
Author
kfan
Definition at line 29 of file utils_join.c.
Referenced by join_split().