Minishell: utils_count.c File Reference
utils_count.c File Reference
#include "minishell.h"
Functions
static int name_count (int count, char *pin)
int sym_count (char c1, char c2, char *pin)
int delimiter_count (char c1, char c2)
Count the length of a delimiter.
Function Documentation
delimiter_count()
int delimiter_count (char c1, char c2)
Count the length of a delimiter.
Returns how long a delimiter is. Delimiters are:
;
&&
||
Parameters
c1 First character of the delimiter
c2 Second character of the delimiter
Returns
int
Return values
len Length of the delimiter
Author
kfan
Definition at line 80 of file utils_count.c.
Referenced by ft_count(), and ft_newstring().
name_count()
static int name_count (int count, char * pin) static
Definition at line 15 of file utils_count.c.
References inside_quote(), and is_sym().
Referenced by sym_count().
sym_count()
int sym_count (char c1, char c2, char * pin)
Definition at line 36 of file utils_count.c.
References name_count().
Referenced by ft_count(), ft_count(), ft_newstring(), ft_newstring(), and redir().