Minishell: utils_ft_split_delimiter.c File Reference
utils_ft_split_delimiter.c File Reference
#include "minishell.h"
Functions
static size_t ft_count (char const *s)
void ft_free (char **array, int i)
static char * ft_newstring (char const *s)
static char ** ft_array (char const *s, char **array)
char ** ft_split_delimiter (char const *s)
Function Documentation
ft_array()
static char ** ft_array (char const * s, char ** array) static
Definition at line 85 of file utils_ft_split_delimiter.c.
References ft_count(), ft_free(), ft_newstring(), and ft_strlen().
Referenced by ft_split_delimiter().
ft_count()
static size_t ft_count (char const * s) static
Definition at line 16 of file utils_ft_split_delimiter.c.
References delimiter_count(), inside_quote(), and is_delimiter().
Referenced by ft_array(), and ft_split_delimiter().
ft_free()
void ft_free (char ** array, int i)
Definition at line 43 of file utils_ft_split_delimiter.c.
Referenced by ft_array().
ft_newstring()
static char * ft_newstring (char const * s) static
Definition at line 56 of file utils_ft_split_delimiter.c.
References delimiter_count(), inside_quote(), and is_delimiter().
Referenced by ft_array().
ft_split_delimiter()
char ** ft_split_delimiter (char const * s)
Definition at line 106 of file utils_ft_split_delimiter.c.
References ft_array(), and ft_count().
Referenced by make_tree().