Minishell: utils.c File Reference
utils.c File Reference
#include "minishell.h"
Functions
char * ft_charjoin (char *s1, char *s2)
Append a character to a string.
int inside_quote (char c, int quote)
Get the current quote state.
void close_unused_fd (t_token **token, int i)
void restore_fd (t_data *data, int *fd)
char * join_cmd (char *src, char *new)
Function Documentation
close_unused_fd()
void close_unused_fd (t_token ** token, int i)
Definition at line 95 of file utils.c.
References t_token::cmds, and t_cmds::fd.
Referenced by make_tree().
ft_charjoin()
char * ft_charjoin (char * s1, char * s2)
Append a character to a string.
This function joins a character to the end of a string. The result is stored as a new malloc'd string and returned.
Parameters
s1 String to join to
s2 Character to join
Returns
char *
Return values
ptr Malloc'd result string
Author
kfan
Definition at line 28 of file utils.c.
References ft_strlcpy(), and ft_strlen().
Referenced by clean_name_char(), clean_name_char(), and join_envp_char().
inside_quote()
int inside_quote (char c, int quote)
Get the current quote state.
Gets the current quote state. List of quote states and their values:
' = 1
" = 2 - ' " = 3
" ' = 4
Returns 0 if the current position is not inside a quotation marked block.
Parameters
c quote character
quote current quote state
Returns
int
Return values
state New quote state
Author
kfan
Definition at line 69 of file utils.c.
References is_quote().
Referenced by clean_name_no_expand(), find_star(), ft_count(), ft_count(), ft_count(), ft_count(), ft_newstring(), ft_newstring(), ft_newstring(), ft_newstring(), loop_str(), and name_count().
join_cmd()
char * join_cmd (char * src, char * new)
Definition at line 132 of file utils.c.
References ft_strjoin().
restore_fd()
void restore_fd (t_data * data, int * fd)
Definition at line 118 of file utils.c.
References t_data::fd, and ft_printf().
Referenced by execute(), and make_tree().