Minishell: utils_is.c File Reference
utils_is.c File Reference
#include "minishell.h"
Functions
int is_sym (char c1, char c2)
Checks which type a symbol is.
int is_delimiter (char c1, char c2)
Checks if a given character is a delimiter.
int is_quote (char c)
Checks if a character is a quote.
int is_space (char c)
Checks if a given character is a space.
int is_pipe (char c)
Checks if a given character is a pipe.
Function Documentation
is_delimiter()
int is_delimiter (char c1, char c2)
Checks if a given character is a delimiter.
Checks if a character is the delimiter of a command. Some delimiters are made up of two characters and therefore require both values to be set so to be recognised properly!
Parameters
c1 first character of the delimiter
c2 second character of the delimiter (may be NULL)
Returns
int
Return values
delim Integer describing the delimiter.
; = 1
&& = 2
|| = 3 if none of these are detected, 0 is returned.
Author
kfan
Definition at line 88 of file utils_is.c.
Referenced by check_temp(), ft_count(), ft_newstring(), and init_token1().
is_pipe()
int is_pipe (char c)
Checks if a given character is a pipe.
Checks if a given character is a '|' pipe character.
Parameters
c character to check
Returns
int
Return values
success 1 if the character is a pipe, 0 otherwise.
Author
kfan
Definition at line 152 of file utils_is.c.
Referenced by check_cmd(), ft_count(), ft_newstring(), and split_cmd().
is_quote()
int is_quote (char c)
Checks if a character is a quote.
Checks if the character is a quotation mark and, if it is, what kind of quotation mark it is (single or double).
Parameters
c character to check
Returns
int
Return values
success 1 for single quotes, 2 for double quotes, 0 otherwise.
Author
kfan
Definition at line 112 of file utils_is.c.
Referenced by clean_name_char(), clean_name_char(), expand_envp(), ft_heredoc(), and inside_quote().
is_space()
int is_space (char c)
Checks if a given character is a space.
Checks if a given character is a space character. This includes ASCII indexes 9 - 13 alongside the ' ' space character.
Parameters
c character to check
Returns
int
Return values
success 1 if the character is a space, 0 otherwise.
Author
kfan
Definition at line 134 of file utils_is.c.
Referenced by check_cmd(), check_new_array(), check_temp(), clean_name(), clean_name_char(), clean_name_char(), clean_name_no_expand(), exit_arg(), ft_array(), ft_count(), ft_newstring(), get_rid_of_extra_space(), init_token1(), join_envp(), redir(), and scan_pipe().
is_sym()
int is_sym (char c1, char c2)
Checks which type a symbol is.
Checks for which type the given symbol is. The list of symbols and their return values are:
$ = 1
| = 2
<< = 3
< = 4
> = 5
>> = 6
; = 7
|| = 8
&& = 9
|| and && are only needed for the bonus. If no symbol is recognised, the function will return 0.
Parameters
c1 First character of the symbol
c2 Second character of the symbol
Returns
int
Return values
type Type of the symbol
Author
kfan
Definition at line 50 of file utils_is.c.
Referenced by ft_count(), ft_newstring(), name_count(), redir(), and scan_pipe().