Minishell: utils_history.c File Reference
utils_history.c File Reference
#include "minishell.h"
Functions
int str_equals (char *str1, char *str2)
Checks if two strings are equal.
void shift_array (char **array, int length)
Shifts an array of strings to the left by one position.
Function Documentation
shift_array()
void shift_array (char ** array, int length)
Shifts an array of strings to the left by one position.
All elements should be malloc'd, the first element will get freed and overwritten!
Parameters
array array to shift
length length of the array
Author
kmautner
Definition at line 53 of file utils_history.c.
Referenced by history_add().
str_equals()
int str_equals (char * str1, char * str2)
Checks if two strings are equal.
This function checks if two strings are equal. They are equal if:
They have the same length
They have the same characters in the same positions
Parameters
str1 first string
str2 second string
Returns
int
Return values
success 0 if the strings are equal, 1 otherwise.
Author
kmautner
Definition at line 30 of file utils_history.c.
References ft_strlen(), and ft_strncmp().
Referenced by builtins_cd(), builtins_env(), builtins_exit(), builtins_export(), builtins_pipe_fd_in(), builtins_pipe_fd_out(), builtins_pwd(), builtins_unset(), check_and_change_path(), check_builtins(), exit_arg(), and history_add().