Minishell: utils_free.c File Reference
utils_free.c File Reference
#include "minishell.h"
Functions
void ft_free_split (char **array)
Frees the result of an ft_split() call.
static void ft_free_struct (t_cmds **cmds, int n)
Frees a command list.
void ft_free_token (t_token **token)
Frees a token.
void small_free (t_token **token, int i)
Small version of ft_free_token()
void free_heredoc (char *suffix, char *prefix, char *temp)
Function Documentation
free_heredoc()
void free_heredoc (char * suffix, char * prefix, char * temp)
Definition at line 146 of file utils_free.c.
Referenced by expand_heredoc().
ft_free_split()
void ft_free_split (char ** array)
Frees the result of an ft_split() call.
Frees a 2-dimensional array like one returned by ft_split(). The array has to be NULL-terminated!
Parameters
array array to free
Author
kfan
Definition at line 25 of file utils_free.c.
Referenced by add_envp(), add_envp_export(), builtins_unset(), check_split_envp(), clean_cmd(), ft_free_struct(), get_files(), join_cmd_2(), join_envp_char(), join_envp_str(), main(), make_tree(), scan_pipe(), split_pipe(), and unset_export().
ft_free_struct()
static void ft_free_struct (t_cmds ** cmds, int n) static
Frees a command list.
Frees a t_cmds command list struct.
Parameters
cmds t_cmds struct to free
n number of commands in the list
t_cmds
Author
kfan
Definition at line 58 of file utils_free.c.
References ft_free_split(), infile(), and outfile().
Referenced by ft_free_token().
ft_free_token()
void ft_free_token (t_token ** token)
Frees a token.
Frees a t_token struct.
Parameters
token t_token struct to free
t_token
Author
kfan
Definition at line 91 of file utils_free.c.
References ft_free_struct().
Referenced by make_tree().
small_free()
void small_free (t_token ** token, int i)
Small version of ft_free_token()
Call this instead of ft_free_token() when the malloc() inside ft_init_token() fails!
Parameters
token token to free
i size of the token data
t_token init_token ft_free_token
Author
kfan
Definition at line 129 of file utils_free.c.
Referenced by init_token().