Minishell: utils_array1.c File Reference
utils_array1.c File Reference
#include "minishell.h"
Functions
void sort_array (char **input)
Sorts an array of strings.
static int ft_strncmp_alpha (const char *s1, const char *s2, size_t n)
Compares two strings.
void sort_array_wildcards (char **input)
char * attach_quote (char *temp)
Add quotation marks around a substring.
void print_array (char **temp)
Debug function to print an array of strings.
Function Documentation
attach_quote()
char * attach_quote (char * temp)
Add quotation marks around a substring.
Adds quotation marks around a literal value inside a string. The literal value is detected by the presence of an '=' sign in front of it. If no '=' is found it returns a duplicate of the original string.
Parameters
temp String to add quotes to
Returns
char*
Return values
new Modified string
Author
kfan
Definition at line 135 of file utils_array1.c.
References ft_calloc(), ft_strdup(), ft_strlcpy(), and ft_strlen().
Referenced by add_envp_export(), and copy_array_prefix().
ft_strncmp_alpha()
static int ft_strncmp_alpha (const char * s1, const char * s2, size_t n) static
Compares two strings.
Compares two strings based on their characters' alphabetical index. Works like strncmp, except that A = a, B = b, etc. Returns 0 if the strings are equal, otherwise it returns the ASCII difference of the first different character.
Parameters
s1 String to compare
s2 String to compare with
n amount of characters (bytes) to compare
Returns
int
Return values
diff Difference between the strings
Author
kfan
Definition at line 70 of file utils_array1.c.
References ft_tolower().
Referenced by sort_array_wildcards().
print_array()
void print_array (char ** temp)
Debug function to print an array of strings.
Debug function to print an array of strings.
Parameters
temp String array to print
Author
kfan
Definition at line 170 of file utils_array1.c.
References ft_printf().
Referenced by builtins_env(), and builtins_export().
sort_array()
void sort_array (char ** input)
Sorts an array of strings.
Sorts an array of strings by their ASCII value. The sorting happens in place!
Parameters
input array to sort
Author
kfan
Definition at line 26 of file utils_array1.c.
References ft_strlen(), ft_strncmp(), and input().
Referenced by add_envp_export(), and init_main().
sort_array_wildcards()
void sort_array_wildcards (char ** input)
Definition at line 94 of file utils_array1.c.
References ft_strlen(), ft_strncmp_alpha(), and input().
Referenced by wildcards().