Minishell: utils_array2.c File Reference
utils_array2.c File Reference
#include "minishell.h"
Functions
static void free_if_failed (char **temp, int i)
Frees a partially initialised malloc'd array of strings.
char ** copy_array_prefix (char **input, int y, int i, int j)
Copies an array of strings, adding a prefix to each string.
char ** copy_array (char **input)
Copies an array of strings.
char ** remove_array (char **input, int index, int y, int j)
Duplicate an array without the value at a given index.
char ** add_array (char **input, char *entry, int y)
Adds a string to an array of strings.
Function Documentation
add_array()
char ** add_array (char ** input, char * entry, int y)
Adds a string to an array of strings.
Copies an array of strings and appends the given string entry to the array.
Parameters
input Array to append to
entry Entry to append
y Counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Appended array
Author
kfan
Definition at line 170 of file utils_array2.c.
References free_if_failed(), ft_strdup(), and input().
Referenced by add_envp(), add_envp_export(), get_files(), join_envp(), join_envp_char(), and join_envp_str().
copy_array()
char ** copy_array (char ** input)
Copies an array of strings.
Copies an array of strings and returns the malloc'd copy. Currently only used to copy envp.
Parameters
input
Returns
char**
Return values
temp Malloc'd copy of the array.
Author
kfan
Definition at line 92 of file utils_array2.c.
References free_if_failed(), ft_strdup(), and input().
Referenced by init_main(), join_cmd_1(), join_cmd_2(), and join_envp_1().
copy_array_prefix()
char ** copy_array_prefix (char ** input, int y, int i, int j)
Copies an array of strings, adding a prefix to each string.
Copies an array of strings and adds the prefix "declare -x " to each string. Also uses attatch_quote() on each string before adding the prefix.
Parameters
input Array to copy
y Counter variable, ALWAYS SET TO 0!
i Counter variable, ALWAYS SET TO 0!
j Counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Malloc'd modified copy of the string array.
Author
kfan
Definition at line 50 of file utils_array2.c.
References attach_quote(), free_if_failed(), ft_strjoin(), and input().
Referenced by init_main().
free_if_failed()
static void free_if_failed (char ** temp, int i) static
Frees a partially initialised malloc'd array of strings.
Frees a malloc'd array of malloc'd strings that hasn't been fully initialised yet. All values before and at the given index will be freed.
Parameters
temp Array to free
i Index of the last initlialised value
Author
kfan
Definition at line 27 of file utils_array2.c.
Referenced by add_array(), copy_array(), copy_array_prefix(), and remove_array().
remove_array()
char ** remove_array (char ** input, int index, int y, int j)
Duplicate an array without the value at a given index.
Duplucates an array of strings, except for the value at a given index. The excluded value will be replaced with NULL in the copy.
Parameters
input array to copy
index index of value to exclude
y counter variable, ALWAYS SET TO 0!
j counter variable, ALWAYS SET TO 0!
Returns
char**
Return values
new Copied array
Author
kfan
Definition at line 131 of file utils_array2.c.
References free_if_failed(), ft_strdup(), and input().
Referenced by add_envp(), builtins_unset(), join_envp_1(), and unset_export().