Minishell: utils_ft_split_cmd.c File Reference
utils_ft_split_cmd.c File Reference
#include "minishell.h"
Functions
static size_t ft_count (char *s)
static char * ft_newstring (char *s)
static char ** ft_array (char *s, char **array)
char ** ft_split_cmd (char *s)
Function Documentation
ft_array()
static char ** ft_array (char * s, char ** array) static
Definition at line 73 of file utils_ft_split_cmd.c.
References ft_count(), ft_free(), ft_newstring(), and ft_strlen().
Referenced by ft_split_cmd().
ft_count()
static size_t ft_count (char * s) static
Definition at line 16 of file utils_ft_split_cmd.c.
References inside_quote(), is_sym(), and sym_count().
Referenced by ft_array(), and ft_split_cmd().
ft_newstring()
static char * ft_newstring (char * s) static
Definition at line 44 of file utils_ft_split_cmd.c.
References inside_quote(), is_sym(), and sym_count().
Referenced by ft_array().
ft_split_cmd()
char ** ft_split_cmd (char * s)
Definition at line 94 of file utils_ft_split_cmd.c.
References ft_array(), and ft_count().
Referenced by split_cmd().